// lib/bookmaker-meta.ts

export type BookmakerMeta = {
  logo: string;
  url: string;
  backgroundColor?: string;
};

export const BOOKMAKER_META: Record<string, BookmakerMeta> = {
  "1xbet": { logo: "/logos/1xbet.svg", url: "https://1xbet.com", backgroundColor: "#ffffff" },
  "888sport": { logo: "/logos/888sport.svg", url: "https://www.888sport.com", backgroundColor: "#ffffff" },
  "10bet": { logo: "/logos/10bet.png", url: "https://10bet.com", backgroundColor: "#ffffff" },
  atg: { logo: "/logos/atg.svg", url: "https://www.atg.se", backgroundColor: "#0357a1" },
  "bally-bet": { logo: "/logos/ballybet.svg", url: "https://www.ballybet.com", backgroundColor: "#ed0000" },
  bet365: { logo: "/logos/bet365.svg", url: "https://www.bet365.com", backgroundColor: "#214036" },
  betano: { logo: "/logos/betano.svg", url: "https://betano.com", backgroundColor: "#ff3c00" },
  betfair: { logo: "/logos/betfair.svg", url: "https://www.betfair.com", backgroundColor: "#ffb60d" },
  "betfair-sportsbook": { logo: "/logos/betfair.svg", url: "https://www.betfair.com/sport", backgroundColor: "#ffb60d" },
  betfred: { logo: "/logos/betfred.png", url: "https://www.betfred.com", backgroundColor: "#ffffff" },
  betmgm: { logo: "/logos/betmgm.svg", url: "https://sports.betmgm.com", backgroundColor: "#0a0a0a" },
  betonline: { logo: "/logos/betonline.svg", url: "https://www.betonline.ag", backgroundColor: "#2d2e2c" },
  betparx: { logo: "/logos/betparx.svg", url: "https://www.betparx.com", backgroundColor: "#1a0533" },
  betright: { logo: "/logos/betright.svg", url: "https://www.betright.com.au", backgroundColor: "#0f1729" },
  betsson: { logo: "/logos/betsson.svg", url: "https://www.betsson.com", backgroundColor: "#ff6600" },
  betus: { logo: "/logos/betus.svg", url: "https://www.betus.com.pa", backgroundColor: "#071226" },
  betvictor: { logo: "/logos/betvictor.svg", url: "https://www.betvictor.com", backgroundColor: "#1d262e" },
  betway: { logo: "/logos/betway.svg", url: "https://www.betway.com", backgroundColor: "#ffffff" },
  betr: { logo: "/logos/betr.svg", url: "https://www.betr.com.au", backgroundColor: "#083bd4" },
  betrivers: { logo: "/logos/betrivers.svg", url: "https://www.betrivers.com", backgroundColor: "#1d355c" },
  betclic: { logo: "/logos/betclic.svg", url: "https://www.betclic.com", backgroundColor: "#d1151e" },
  bovada: { logo: "/logos/bovada.svg", url: "https://www.bovada.lv", backgroundColor: "#ffffff" },
  boylesports: { logo: "/logos/boylesports.svg", url: "https://www.boylesports.com", backgroundColor: "#2500f5" },
  bwin: { logo: "/logos/bwin.svg", url: "https://bwin.com", backgroundColor: "#000000" },
  campobet: { logo: "/logos/campobet.svg", url: "https://www.campobet.com", backgroundColor: "#104a2d" },
  casumo: { logo: "/logos/casumo.svg", url: "https://www.casumo.com", backgroundColor: "#32007d" },
  codere: { logo: "/logos/codere.svg", url: "https://www.codere.com", backgroundColor: "#252a30" },
  coolbet: { logo: "/logos/coolbet.svg", url: "https://www.coolbet.com", backgroundColor: "#2b2b36" },
  coral: { logo: "/logos/coral.svg", url: "https://sports.coral.co.uk", backgroundColor: "#084d8c" },
  draftkings: { logo: "/logos/draftkings.png", url: "https://sportsbook.draftkings.com", backgroundColor: "#ffffff" },
  everygame: { logo: "/logos/everygame.svg", url: "https://www.everygame.eu", backgroundColor: "#0d0d0d" },
  fanduel: { logo: "/logos/fanduel.png", url: "https://sportsbook.fanduel.com", backgroundColor: "#ffffff" },
  "grosvenor-casinos": { logo: "/logos/grosvenor.svg", url: "https://www.grosvenorcasinos.com", backgroundColor: "#080808" },
  gtbets: { logo: "/logos/gtbets.png", url: "https://www.gtbets.ag", backgroundColor: "#01133b" },
  hajper: { logo: "/logos/hajper.svg", url: "https://www.hajper.com", backgroundColor: "#0d194f" },
  "hard-rock-bet": { logo: "/logos/hardrockbet.svg", url: "https://app.hardrock.bet", backgroundColor: "#1b191c" },
  ladbrokes: { logo: "/logos/ladbrokes.svg", url: "https://www.ladbrokes.com", backgroundColor: "#f01d27" },
  leovegas: { logo: "/logos/leovegas.svg", url: "https://www.leovegas.com", backgroundColor: "#ed4700" },
  livescorebet: { logo: "/logos/livescorebet.jpg", url: "https://www.livescorebet.com", backgroundColor: "#ffffff" },
  lowvig: { logo: "/logos/lowvig.svg", url: "https://www.lowvig.ag", backgroundColor: "#01153d" },
  marathonbet: { logo: "/logos/marathonbet.png", url: "https://www.marathonbet.com", backgroundColor: "#013d78" },
  matchbook: { logo: "/logos/matchbook.png", url: "https://www.matchbook.com", backgroundColor: "#e81e25" },
  "mr-green": { logo: "/logos/mrgreen.svg", url: "https://www.mrgreen.com", backgroundColor: "#015436" },
  mybookie: { logo: "/logos/mybookie.png", url: "https://www.mybookie.ag", backgroundColor: "#242526" },
  neds: { logo: "/logos/neds.svg", url: "https://www.neds.com.au", backgroundColor: "#f55d05" },
  netbet: { logo: "/logos/netbet.png", url: "https://www.netbet.fr", backgroundColor: "#363845" },
  nordicbet: { logo: "/logos/nordicbet.svg", url: "https://www.nordicbet.com", backgroundColor: "#0067b9" },
  "paddy-power": { logo: "/logos/paddypower.svg", url: "https://www.paddypower.com", backgroundColor: "#ffffff" },
  pinnacle: { logo: "/logos/pinnacle.svg", url: "https://www.pinnacle.com", backgroundColor: "#09192e" },
  playup: { logo: "/logos/playup.svg", url: "https://www.playup.com.au", backgroundColor: "#191c21" },
  pmu: { logo: "/logos/pmu.png", url: "https://pmu.fr", backgroundColor: "#ffffff" },
  pointsbet: { logo: "/logos/pointsbet.svg", url: "https://pointsbet.com", backgroundColor: "#0a0a0a" },
  skybet: { logo: "/logos/skybet.svg", url: "https://www.skybet.com", backgroundColor: "#ffffff" },
  smarkets: { logo: "/logos/smarkets.svg", url: "https://smarkets.com", backgroundColor: "#ffffff" },
  sportsbet: { logo: "/logos/sportsbet.jpg", url: "https://www.sportsbet.com.au", backgroundColor: "#0067ab" },
  "svenska-spel": { logo: "/logos/svenskaspel.svg", url: "https://www.svenskaspel.se", backgroundColor: "#a10812" },
  tab: { logo: "/logos/tab.png", url: "https://www.tab.com.au", backgroundColor: "#ffffff" },
  tabtouch: { logo: "/logos/tabtouch.svg", url: "https://www.tabtouch.com.au", backgroundColor: "#522d6e" },
  thescore: { logo: "/logos/thescorebet.svg", url: "https://thescore.bet", backgroundColor: "#101d2e" },
  tipico: { logo: "/logos/tipico.svg", url: "https://www.tipico.com", backgroundColor: "#ffffff" },
  unibet: { logo: "/logos/unibet.png", url: "https://www.unibet.com", backgroundColor: "#147a45" },
  "virgin-bet": { logo: "/logos/virginbet.jpeg", url: "https://www.virginbet.com", backgroundColor: "#cc080f" },
  "william-hill": { logo: "/logos/williamhill.png", url: "https://www.williamhill.com", backgroundColor: "#060a29" },
  winamax: { logo: "/logos/winamax.png", url: "https://www.winamax.fr", backgroundColor: "#e6e6e6" },
  stake: { logo: "/logos/stake.svg", url: "https://stake.com", backgroundColor: "#1a2d38" },
  "22bet": { logo: "/logos/22bet.png", url: "https://22bet.com", backgroundColor: "#054247" },
  "20bet": { logo: "/logos/20bet.png", url: "https://20bet.com", backgroundColor: "#0d1d33" },
  melbet: { logo: "/logos/melbet.svg", url: "https://melbet.com", backgroundColor: "#212121" },
  betwinner: { logo: "/logos/betwinner.svg", url: "https://betwinner.com", backgroundColor: "#1a664a" },
  parimatch: { logo: "/logos/parimatch.svg", url: "https://parimatch.com", backgroundColor: "#141414" },
  dafabet: { logo: "/logos/dafabet.svg", url: "https://www.dafabet.com", backgroundColor: "#b00000" },
  "sportsbet-io": { logo: "/logos/sportsbetio.svg", url: "https://sportsbet.io", backgroundColor: "#2d333b" },
  cloudbet: { logo: "/logos/cloudbet.svg", url: "https://www.cloudbet.com", backgroundColor: "#120f12" },
  sbotop: { logo: "/logos/sbotop.svg", url: "https://www.sbotop.com", backgroundColor: "#002e6b" },
  m88: { logo: "/logos/m88.svg", url: "https://www.m88.com", backgroundColor: "#1a202b" },
  fun88: { logo: "/logos/fun88.png", url: "https://fun88.com/", backgroundColor: "#ffffff" },
  novibet: { logo: "/logos/novibet.svg", url: "https://www.novibet.com", backgroundColor: "#0a1324" },
  stoiximan: { logo: "/logos/stoiximan.svg", url: "https://stoiximan.gr", backgroundColor: "#0055ff" },
  superbet: { logo: "/logos/superbet.svg", url: "https://superbet.com", backgroundColor: "#360103" },
  "bet-at-home": { logo: "/logos/betathome.svg", url: "https://www.bet-at-home.com/", backgroundColor: "#ffffff" },
  interwetten: { logo: "/logos/interwetten.svg", url: "https://www.interwetten.com/", backgroundColor: "#ffd000" },
  expekt: { logo: "/logos/expekt.svg", url: "https://www.expekt.se", backgroundColor: "#ff8000" },
  betsafe: { logo: "/logos/betsafe.svg", url: "https://www.betsafe.com", backgroundColor: "#121212" },
  
};

export const FALLBACK_BOOKMAKER_META: BookmakerMeta = {
  logo: "/logos/default-bookmaker.svg",
  url: "#",
};