export type Market = "all" | "us" | "uk" | "eu" | "fr" | "se" | "au";

export type RegionalBookmakerRow = {
  bookmaker_id: string;
  bookmaker_key: string;
  bookmaker_title: string;
  market: Exclude<Market, "all">;
  samples: number;
  average_margin_percent: number;
  logo: string;
  url: string;
};

type RawRegionalBookmakerRow = Omit<RegionalBookmakerRow, "logo" | "url">;

type BookmakerMeta = {
  logo: string;
  url: string;
};

const BOOKMAKER_META: Record<string, BookmakerMeta> = {
  "1xbet": { logo: "/logos/1xbet.svg", url: "https://1xbet.com" },
  "888sport": { logo: "/logos/888sport.svg", url: "https://www.888sport.com" },
  atg: { logo: "/logos/atg.svg", url: "https://www.atg.se" },
  ballybet: { logo: "/logos/ballybet.svg", url: "https://www.ballybet.com" },
  betfair: { logo: "/logos/betfair.svg", url: "https://www.betfair.com" },
  betfair_sportsbook: { logo: "/logos/betfair.svg", url: "https://www.betfair.com/sport" },
  betfred: { logo: "/logos/betfred.svg", url: "https://www.betfred.com" },
  betmgm: { logo: "/logos/betmgm.svg", url: "https://sports.betmgm.com" },
  betonline: { logo: "/logos/betonline.svg", url: "https://www.betonline.ag" },
  betparx: { logo: "/logos/betparx.svg", url: "https://www.betparx.com" },
  betright: { logo: "/logos/betright.svg", url: "https://www.betright.com.au" },
  betsson: { logo: "/logos/betsson.svg", url: "https://www.betsson.com" },
  betus: { logo: "/logos/betus.svg", url: "https://www.betus.com.pa" },
  betvictor: { logo: "/logos/betvictor.svg", url: "https://www.betvictor.com" },
  betway: { logo: "/logos/betway.svg", url: "https://www.betway.com" },
  betr: { logo: "/logos/betr.svg", url: "https://www.betr.com.au" },
  betrivers: { logo: "/logos/betrivers.svg", url: "https://www.betrivers.com" },
  betclic: { logo: "/logos/betclic.svg", url: "https://www.betclic.com" },
  betfred_us: { logo: "/logos/betfred.svg", url: "https://www.betfredsports.com" },
  betonlineag: { logo: "/logos/betonline.svg", url: "https://www.betonline.ag" },
  betright_au: { logo: "/logos/betright.svg", url: "https://www.betright.com.au" },
  betus_us: { logo: "/logos/betus.svg", url: "https://www.betus.com.pa" },
  betvictor_uk: { logo: "/logos/betvictor.svg", url: "https://www.betvictor.com" },
  betway_uk: { logo: "/logos/betway.svg", url: "https://www.betway.com" },
  betsson_se: { logo: "/logos/betsson.svg", url: "https://www.betsson.com" },
  betsson_eu: { logo: "/logos/betsson.svg", url: "https://www.betsson.com" },
  betclic_fr: { logo: "/logos/betclic.svg", url: "https://www.betclic.fr" },
  betclic_fr_eu: { logo: "/logos/betclic.svg", url: "https://www.betclic.fr" },
  betonlineag_us: { logo: "/logos/betonline.svg", url: "https://www.betonline.ag" },
  betonlineag_eu: { logo: "/logos/betonline.svg", url: "https://www.betonline.ag" },
  betfair_ex_au: { logo: "/logos/betfair.svg", url: "https://www.betfair.com" },
  betfair_ex_eu: { logo: "/logos/betfair.svg", url: "https://www.betfair.com" },
  betfair_ex_uk: { logo: "/logos/betfair.svg", url: "https://www.betfair.com" },
  betfair_sb_uk: { logo: "/logos/betfair.svg", url: "https://www.betfair.com/sport" },
  bovada: { logo: "/logos/bovada.svg", url: "https://www.bovada.lv" },
  boylesports: { logo: "/logos/boylesports.svg", url: "https://www.boylesports.com" },
  campobet: { logo: "/logos/campobet.svg", url: "https://www.campobet.com" },
  casumo: { logo: "/logos/casumo.svg", url: "https://www.casumo.com" },
  codere: { logo: "/logos/codere.svg", url: "https://www.codere.com" },
  coolbet: { logo: "/logos/coolbet.svg", url: "https://www.coolbet.com" },
  coral: { logo: "/logos/coral.svg", url: "https://sports.coral.co.uk" },
  draftkings: { logo: "/logos/draftkings.svg", url: "https://sportsbook.draftkings.com" },
  everygame: { logo: "/logos/everygame.svg", url: "https://www.everygame.eu" },
  fanduel: { logo: "/logos/fanduel.svg", url: "https://sportsbook.fanduel.com" },
  grosvenor: { logo: "/logos/grosvenor.svg", url: "https://www.grosvenorcasinos.com" },
  gtbets: { logo: "/logos/gtbets.svg", url: "https://www.gtbets.eu" },
  hajper: { logo: "/logos/hajper.svg", url: "https://www.hajper.com" },
  hardrockbet: { logo: "/logos/hardrockbet.svg", url: "https://app.hardrock.bet" },
  ladbrokes: { logo: "/logos/ladbrokes.svg", url: "https://www.ladbrokes.com" },
  leovegas: { logo: "/logos/leovegas.svg", url: "https://www.leovegas.com" },
  livescorebet: { logo: "/logos/livescorebet.svg", url: "https://www.livescorebet.com" },
  lowvig: { logo: "/logos/lowvig.svg", url: "https://www.lowvig.ag" },
  marathonbet: { logo: "/logos/marathonbet.svg", url: "https://www.marathonbet.com" },
  matchbook: { logo: "/logos/matchbook.svg", url: "https://www.matchbook.com" },
  mrgreen: { logo: "/logos/mrgreen.svg", url: "https://www.mrgreen.com" },
  mybookie: { logo: "/logos/mybookie.svg", url: "https://www.mybookie.ag" },
  neds: { logo: "/logos/neds.svg", url: "https://www.neds.com.au" },
  netbet: { logo: "/logos/netbet.svg", url: "https://www.netbet.fr" },
  nordicbet: { logo: "/logos/nordicbet.svg", url: "https://www.nordicbet.com" },
  paddypower: { logo: "/logos/paddypower.svg", url: "https://www.paddypower.com" },
  pinnacle: { logo: "/logos/pinnacle.svg", url: "https://www.pinnacle.com" },
  playup: { logo: "/logos/playup.svg", url: "https://www.playup.com.au" },
  pmu: { logo: "/logos/pmu.svg", url: "https://paris-sportifs.pmu.fr" },
  pointsbet: { logo: "/logos/pointsbet.svg", url: "https://pointsbet.com" },
  skynet: { logo: "/logos/skybet.svg", url: "https://www.skybet.com" },
  skybet: { logo: "/logos/skybet.svg", url: "https://www.skybet.com" },
  smarkets: { logo: "/logos/smarkets.svg", url: "https://smarkets.com" },
  sportsbet: { logo: "/logos/sportsbet.svg", url: "https://www.sportsbet.com.au" },
  svenskaspel: { logo: "/logos/svenskaspel.svg", url: "https://www.svenskaspel.se" },
  tab: { logo: "/logos/tab.svg", url: "https://www.tab.com.au" },
  tabtouch: { logo: "/logos/tabtouch.svg", url: "https://www.tabtouch.com.au" },
  thescorebet: { logo: "/logos/thescorebet.svg", url: "https://thescore.bet" },
  tipico: { logo: "/logos/tipico.svg", url: "https://www.tipico.com" },
  unibet: { logo: "/logos/unibet.svg", url: "https://www.unibet.com" },
  virginbet: { logo: "/logos/virginbet.svg", url: "https://www.virginbet.com" },
  williamhill: { logo: "/logos/williamhill.svg", url: "https://www.williamhill.com" },
  winamax: { logo: "/logos/winamax.svg", url: "https://www.winamax.fr" },
};

const FALLBACK_META: BookmakerMeta = {
  logo: "/logos/default-bookmaker.svg",
  url: "#",
};

const rawBookmakerMarginData: RawRegionalBookmakerRow[] = [
  { bookmaker_id: "betfair", bookmaker_key: "betfair_ex_au", bookmaker_title: "Betfair (Exchange)", market: "au", samples: 6, average_margin_percent: 1.059 },
  { bookmaker_id: "unibet", bookmaker_key: "unibet_au", bookmaker_title: "Unibet", market: "au", samples: 6, average_margin_percent: 5.332 },
  { bookmaker_id: "tabtouch", bookmaker_key: "tabtouch", bookmaker_title: "TABtouch", market: "au", samples: 6, average_margin_percent: 5.332 },
  { bookmaker_id: "pointsbet", bookmaker_key: "pointsbetau", bookmaker_title: "PointsBet", market: "au", samples: 6, average_margin_percent: 5.754 },
  { bookmaker_id: "betright", bookmaker_key: "betright", bookmaker_title: "Bet Right", market: "au", samples: 6, average_margin_percent: 6.207 },
  { bookmaker_id: "sportsbet", bookmaker_key: "sportsbet", bookmaker_title: "Sportsbet", market: "au", samples: 6, average_margin_percent: 6.211 },
  { bookmaker_id: "neds", bookmaker_key: "neds", bookmaker_title: "Neds", market: "au", samples: 6, average_margin_percent: 6.651 },
  { bookmaker_id: "ladbrokes", bookmaker_key: "ladbrokes_au", bookmaker_title: "Ladbrokes", market: "au", samples: 6, average_margin_percent: 6.651 },
  { bookmaker_id: "betr", bookmaker_key: "betr_au", bookmaker_title: "Betr", market: "au", samples: 6, average_margin_percent: 7.104 },
  { bookmaker_id: "tab", bookmaker_key: "tab", bookmaker_title: "TAB", market: "au", samples: 6, average_margin_percent: 7.281 },
  { bookmaker_id: "playup", bookmaker_key: "playup", bookmaker_title: "PlayUp", market: "au", samples: 6, average_margin_percent: 7.404 },

  { bookmaker_id: "matchbook", bookmaker_key: "matchbook_eu", bookmaker_title: "Matchbook (Exchange)", market: "eu", samples: 6, average_margin_percent: 0.992 },
  { bookmaker_id: "betfair", bookmaker_key: "betfair_ex_eu", bookmaker_title: "Betfair (Exchange)", market: "eu", samples: 6, average_margin_percent: 1.059 },
  { bookmaker_id: "1xbet", bookmaker_key: "1xbet", bookmaker_title: "1xBet", market: "eu", samples: 6, average_margin_percent: 1.499 },
  { bookmaker_id: "unibet", bookmaker_key: "unibet_nl", bookmaker_title: "Unibet", market: "eu", samples: 6, average_margin_percent: 2.221 },
  { bookmaker_id: "unibet", bookmaker_key: "unibet_se_eu", bookmaker_title: "Unibet", market: "eu", samples: 6, average_margin_percent: 2.636 },
  { bookmaker_id: "marathonbet", bookmaker_key: "marathonbet", bookmaker_title: "Marathonbet", market: "eu", samples: 6, average_margin_percent: 3.177 },
  { bookmaker_id: "pinnacle", bookmaker_key: "pinnacle_eu", bookmaker_title: "Pinnacle", market: "eu", samples: 6, average_margin_percent: 3.480 },
  { bookmaker_id: "betonline", bookmaker_key: "betonlineag_eu", bookmaker_title: "BetOnline", market: "eu", samples: 6, average_margin_percent: 3.499 },
  { bookmaker_id: "coolbet", bookmaker_key: "coolbet_eu", bookmaker_title: "Coolbet", market: "eu", samples: 6, average_margin_percent: 3.902 },
  { bookmaker_id: "betsson", bookmaker_key: "betsson_eu", bookmaker_title: "Betsson", market: "eu", samples: 6, average_margin_percent: 4.123 },
  { bookmaker_id: "nordicbet", bookmaker_key: "nordicbet", bookmaker_title: "NordicBet", market: "eu", samples: 6, average_margin_percent: 4.123 },
  { bookmaker_id: "leovegas", bookmaker_key: "leovegas_se", bookmaker_title: "LeoVegas", market: "eu", samples: 6, average_margin_percent: 4.257 },
  { bookmaker_id: "codere", bookmaker_key: "codere_it", bookmaker_title: "Codere", market: "eu", samples: 6, average_margin_percent: 5.073 },
  { bookmaker_id: "tipico", bookmaker_key: "tipico", bookmaker_title: "Tipico", market: "eu", samples: 6, average_margin_percent: 6.060 },
  { bookmaker_id: "winamax", bookmaker_key: "winamax_de", bookmaker_title: "Winamax", market: "eu", samples: 6, average_margin_percent: 6.749 },
  { bookmaker_id: "betclic", bookmaker_key: "betclic_fr_eu", bookmaker_title: "Betclic", market: "eu", samples: 6, average_margin_percent: 6.927 },
  { bookmaker_id: "mybookie", bookmaker_key: "mybookieag_eu", bookmaker_title: "MyBookie", market: "eu", samples: 6, average_margin_percent: 6.999 },
  { bookmaker_id: "pmu", bookmaker_key: "pmu_fr_eu", bookmaker_title: "PMU", market: "eu", samples: 6, average_margin_percent: 7.491 },
  { bookmaker_id: "winamax", bookmaker_key: "winamax_fr_eu", bookmaker_title: "Winamax", market: "eu", samples: 6, average_margin_percent: 7.881 },
  { bookmaker_id: "unibet", bookmaker_key: "unibet_fr_eu", bookmaker_title: "Unibet", market: "eu", samples: 6, average_margin_percent: 7.967 },
  { bookmaker_id: "888sport", bookmaker_key: "888sport_eu", bookmaker_title: "888sport", market: "eu", samples: 6, average_margin_percent: 8.778 },
  { bookmaker_id: "williamhill", bookmaker_key: "williamhill_eu", bookmaker_title: "William Hill", market: "eu", samples: 6, average_margin_percent: 8.778 },
  { bookmaker_id: "everygame", bookmaker_key: "everygame", bookmaker_title: "Everygame", market: "eu", samples: 6, average_margin_percent: 9.629 },

  { bookmaker_id: "betclic", bookmaker_key: "betclic_fr", bookmaker_title: "Betclic", market: "fr", samples: 6, average_margin_percent: 6.927 },
  { bookmaker_id: "pmu", bookmaker_key: "pmu_fr", bookmaker_title: "PMU", market: "fr", samples: 6, average_margin_percent: 7.491 },
  { bookmaker_id: "winamax", bookmaker_key: "winamax_fr", bookmaker_title: "Winamax", market: "fr", samples: 6, average_margin_percent: 7.881 },
  { bookmaker_id: "unibet", bookmaker_key: "unibet_fr", bookmaker_title: "Unibet", market: "fr", samples: 6, average_margin_percent: 7.967 },
  { bookmaker_id: "netbet", bookmaker_key: "netbet", bookmaker_title: "NetBet", market: "fr", samples: 6, average_margin_percent: 11.177 },

  { bookmaker_id: "atg", bookmaker_key: "atg_se", bookmaker_title: "ATG", market: "se", samples: 6, average_margin_percent: 2.636 },
  { bookmaker_id: "svenskaspel", bookmaker_key: "svenska_spel", bookmaker_title: "Svenska Spel", market: "se", samples: 6, average_margin_percent: 2.636 },
  { bookmaker_id: "unibet", bookmaker_key: "unibet_se", bookmaker_title: "Unibet", market: "se", samples: 6, average_margin_percent: 2.636 },
  { bookmaker_id: "pinnacle", bookmaker_key: "pinnacle_se", bookmaker_title: "Pinnacle", market: "se", samples: 6, average_margin_percent: 3.480 },
  { bookmaker_id: "coolbet", bookmaker_key: "coolbet_se", bookmaker_title: "Coolbet", market: "se", samples: 6, average_margin_percent: 3.902 },
  { bookmaker_id: "betsson", bookmaker_key: "betsson_se", bookmaker_title: "Betsson", market: "se", samples: 6, average_margin_percent: 4.123 },
  { bookmaker_id: "nordicbet", bookmaker_key: "nordicbet_se", bookmaker_title: "NordicBet", market: "se", samples: 6, average_margin_percent: 4.123 },
  { bookmaker_id: "leovegas", bookmaker_key: "leovegas_se_domestic", bookmaker_title: "LeoVegas", market: "se", samples: 6, average_margin_percent: 4.257 },
  { bookmaker_id: "campobet", bookmaker_key: "campobet_se", bookmaker_title: "CampoBet", market: "se", samples: 6, average_margin_percent: 4.977 },
  { bookmaker_id: "hajper", bookmaker_key: "hajper_se", bookmaker_title: "Hajper", market: "se", samples: 6, average_margin_percent: 6.109 },
  { bookmaker_id: "mrgreen", bookmaker_key: "mrgreen_se", bookmaker_title: "Mr Green", market: "se", samples: 6, average_margin_percent: 8.778 },
  { bookmaker_id: "888sport", bookmaker_key: "888sport_se", bookmaker_title: "888sport", market: "se", samples: 6, average_margin_percent: 8.778 },

  { bookmaker_id: "matchbook", bookmaker_key: "matchbook_uk", bookmaker_title: "Matchbook (Exchange)", market: "uk", samples: 6, average_margin_percent: 0.905 },
  { bookmaker_id: "betfair", bookmaker_key: "betfair_ex_uk", bookmaker_title: "Betfair (Exchange)", market: "uk", samples: 6, average_margin_percent: 0.972 },
  { bookmaker_id: "smarkets", bookmaker_key: "smarkets", bookmaker_title: "Smarkets (Exchange)", market: "uk", samples: 6, average_margin_percent: 1.576 },
  { bookmaker_id: "casumo", bookmaker_key: "casumo", bookmaker_title: "Casumo", market: "uk", samples: 6, average_margin_percent: 5.346 },
  { bookmaker_id: "grosvenor", bookmaker_key: "grosvenor", bookmaker_title: "Grosvenor", market: "uk", samples: 6, average_margin_percent: 5.346 },
  { bookmaker_id: "betfred", bookmaker_key: "betfred_uk", bookmaker_title: "Betfred", market: "uk", samples: 6, average_margin_percent: 5.903 },
  { bookmaker_id: "coral", bookmaker_key: "coral", bookmaker_title: "Coral", market: "uk", samples: 6, average_margin_percent: 6.084 },
  { bookmaker_id: "betway", bookmaker_key: "betway", bookmaker_title: "Betway", market: "uk", samples: 6, average_margin_percent: 6.370 },
  { bookmaker_id: "leovegas", bookmaker_key: "leovegas_uk", bookmaker_title: "LeoVegas", market: "uk", samples: 6, average_margin_percent: 6.458 },
  { bookmaker_id: "ladbrokes", bookmaker_key: "ladbrokes_uk", bookmaker_title: "Ladbrokes", market: "uk", samples: 6, average_margin_percent: 6.840 },
  { bookmaker_id: "paddypower", bookmaker_key: "paddypower", bookmaker_title: "Paddy Power", market: "uk", samples: 6, average_margin_percent: 6.872 },
  { bookmaker_id: "betvictor", bookmaker_key: "betvictor", bookmaker_title: "BetVictor", market: "uk", samples: 6, average_margin_percent: 7.524 },
  { bookmaker_id: "skybet", bookmaker_key: "skybet", bookmaker_title: "Sky Bet", market: "uk", samples: 6, average_margin_percent: 7.723 },
  { bookmaker_id: "boylesports", bookmaker_key: "boylesports", bookmaker_title: "BoyleSports", market: "uk", samples: 6, average_margin_percent: 7.764 },
  { bookmaker_id: "888sport", bookmaker_key: "888sport_uk", bookmaker_title: "888sport", market: "uk", samples: 6, average_margin_percent: 8.511 },
  { bookmaker_id: "williamhill", bookmaker_key: "williamhill_uk", bookmaker_title: "William Hill", market: "uk", samples: 6, average_margin_percent: 8.511 },
  { bookmaker_id: "virginbet", bookmaker_key: "virginbet", bookmaker_title: "Virgin Bet", market: "uk", samples: 6, average_margin_percent: 11.053 },
  { bookmaker_id: "livescorebet", bookmaker_key: "livescorebet", bookmaker_title: "LiveScore Bet", market: "uk", samples: 6, average_margin_percent: 11.053 },
  { bookmaker_id: "betfair_sportsbook", bookmaker_key: "betfair_sb_uk", bookmaker_title: "Betfair Sportsbook", market: "uk", samples: 6, average_margin_percent: 14.383 },

  { bookmaker_id: "lowvig", bookmaker_key: "lowvig", bookmaker_title: "LowVig", market: "us", samples: 5, average_margin_percent: 3.503 },
  { bookmaker_id: "betonline", bookmaker_key: "betonlineag_us", bookmaker_title: "BetOnline", market: "us", samples: 5, average_margin_percent: 3.503 },
  { bookmaker_id: "draftkings", bookmaker_key: "draftkings", bookmaker_title: "DraftKings", market: "us", samples: 5, average_margin_percent: 4.719 },
  { bookmaker_id: "bovada", bookmaker_key: "bovada", bookmaker_title: "Bovada", market: "us", samples: 5, average_margin_percent: 5.394 },
  { bookmaker_id: "betus", bookmaker_key: "betus", bookmaker_title: "BetUS", market: "us", samples: 5, average_margin_percent: 5.394 },
  { bookmaker_id: "betrivers", bookmaker_key: "betrivers", bookmaker_title: "BetRivers", market: "us", samples: 5, average_margin_percent: 5.762 },
  { bookmaker_id: "betmgm", bookmaker_key: "betmgm", bookmaker_title: "BetMGM", market: "us", samples: 5, average_margin_percent: 6.152 },
  { bookmaker_id: "fanduel", bookmaker_key: "fanduel", bookmaker_title: "FanDuel", market: "us", samples: 5, average_margin_percent: 6.419 },
  { bookmaker_id: "mybookie", bookmaker_key: "mybookieag_us", bookmaker_title: "MyBookie", market: "us", samples: 5, average_margin_percent: 7.007 },
  { bookmaker_id: "hardrockbet", bookmaker_key: "hardrockbet", bookmaker_title: "Hard Rock Bet", market: "us", samples: 6, average_margin_percent: 4.957 },
  { bookmaker_id: "ballybet", bookmaker_key: "ballybet", bookmaker_title: "Bally Bet", market: "us", samples: 6, average_margin_percent: 5.346 },
  { bookmaker_id: "betparx", bookmaker_key: "betparx", bookmaker_title: "betPARX", market: "us", samples: 6, average_margin_percent: 5.346 },
  { bookmaker_id: "thescorebet", bookmaker_key: "thescorebet", bookmaker_title: "theScore Bet", market: "us", samples: 6, average_margin_percent: 6.896 },
];

export const bookmakerMarginData: RegionalBookmakerRow[] = rawBookmakerMarginData.map((row) => {
  const meta = BOOKMAKER_META[row.bookmaker_id] ?? FALLBACK_META;

  return {
    ...row,
    logo: meta.logo,
    url: meta.url,
  };
});