// lib/bookmaker-availability.ts

import type { CountrySlug, RegionSlug } from "@/lib/bookmaker-locations";
import { Albert_Sans } from "next/font/google";

export type AvailabilityMode =
  | "locally_licensed"
  | "explicit_allowed"
  | "global_except_restricted"
  | "region_except_restricted"
  | "unknown";

export type AvailabilityConfidence =
  | "high"
  | "medium"
  | "low";

export type BookmakerAvailability = {
  regions: RegionSlug[];

  mode: AvailabilityMode;

  licensedCountries?: CountrySlug[];
  restrictedCountries?: CountrySlug[];

  confidence: AvailabilityConfidence;

  notes?: string;
};

export const bookmakerAvailability: Record<string, BookmakerAvailability> = {
    betfair: {
        regions: ["europe", "asia", "africa", "south-america", "north-america", "oceania"],
        mode: "locally_licensed",
        licensedCountries: [
            "united-kingdom",
            "andorra",
            "argentina",
            "australia",
            "austria",
            "azerbaijan",
            "bahamas",
            "belarus",
            "bermuda",
            "bolivia",
            "bosnia-and-hercegovina",
            "botswana",
            "cambodia",
            "cayman-islands",
            "chile",
            "costa-rica",
            "denmark",
            "dominican-republic",
            "egypt",
            "el-salvador",
            "faroe-islands",
            "finland",
            "gibraltar",
            "guatemala",
            "honduras",
            "iceland",
            "indonesia",
            "ireland",
            "italy",
            "jamaica",
            "kyrgyzstan",
            "kazakhstan",
            "lebanon",
            "liechtenstein",
            "lithuania",
            "luxembourg",
            "malta",
            "mauritius",
            "moldova",
            "monaco",
            "mongolia",
            "nepal",
            "sint-maarten",
            "curacao",
            "aruba",
            "new-zealand",
            "nicaragua",
            "pakistan",
            "panama",
            "paraguay",
            "philippines",
            "romania",
            "senegal",
            "seychelles",
            "slovakia",
            "south-korea",
            "spain",
            "oman",
            "thailand",
            "trinidad-and-tobago",
            "ukraine",
            "uruguay",
            "uzbekistan",
            "venezuela",
            "vietnam",
            "british-virgin-islands"
        ],
        confidence: "high",
        notes: "International exchange available in many countries worldwide."
    },
    unibet: {
        regions: ["europe"],
        mode: "locally_licensed",
        licensedCountries: [
            "united-kingdom", 
            "gibraltar", 
            "isle-of-man", 
            "jersey",
            "guernsey",
            "australia",
            "belgium",
            "denmark",
            "estonia",
            "finland",
            "ireland",
            "malta",
            "netherlands",
            "romania",
            "sweden",
            "guadeloupe",
            "guyana",
            "martinique",
            "reunion",
            "mayotte",
            "saint-barthelemy",
            "saint-martin",
            "saint-pierre-and-miquelon",
            "monaco",
            "sint-maarten"
        ],
        confidence: "high",
        notes: "European-focused licensed operator"
    },
    tabtouch: {
        regions: ["oceania"],
        mode: "locally_licensed",
        licensedCountries: [
            "australia", 
            "norfolk-island", 
            "christmas-island", 
            "cocos-islands"
        ],
        confidence: "high",
        notes: "Australian licensed operator"
    },
    pointsbet: {
        regions: ["oceania"],
        mode: "locally_licensed",
        licensedCountries: [
            "australia", 
            "norfolk-island", 
            "christmas-island", 
            "cocos-islands"
        ],
        confidence: "high",
        notes: "Australian licensed operator"
    },
    betright: {
        regions: ["oceania"],
        mode: "locally_licensed",
        licensedCountries: [
            "australia", 
            "norfolk-island", 
            "christmas-island", 
            "cocos-islands"
        ],
        confidence: "high",
        notes: "Australian licensed operator"
    },
    sportsbet: {
        regions: ["oceania"],
        mode: "locally_licensed",
        licensedCountries: [
            "australia", 
            "norfolk-island", 
            "christmas-island", 
            "cocos-islands"
        ],
        confidence: "high",
        notes: "Australian licensed operator"
    },
    neds: {
        regions: ["oceania"],
        mode: "locally_licensed",
        licensedCountries: [
            "australia", 
            "norfolk-island", 
            "christmas-island", 
            "cocos-islands",
            "new-zealand",
            "tokelau",
            "niue",
            "cook-islands"
        ],
        confidence: "high",
        notes: "Australian/New Zealand licensed operator"
    },
    ladbrokes: {
        regions: ["oceania", "europe"],
        mode: "locally_licensed",
        licensedCountries: [
            "australia", 
            "norfolk-island", 
            "christmas-island", 
            "cocos-islands",
            "new-zealand",
            "tokelau",
            "niue",
            "cook-islands",
            "gibraltar",
            "jersey",
            "ireland",
            "united-kingdom"
        ],
        confidence: "high",
        notes: "UK/Australian licensed operator"
    },
    betr: {
        regions: ["oceania"],
        mode: "locally_licensed",
        licensedCountries: [
            "australia", 
            "norfolk-island", 
            "christmas-island", 
            "cocos-islands",
        ],
        confidence: "high",
        notes: "Australian licensed operator"
    },
    tab: {
        regions: ["oceania"],
        mode: "locally_licensed",
        licensedCountries: [
            "australia", 
            "norfolk-island", 
            "christmas-island", 
            "cocos-islands",
        ],
        confidence: "high",
        notes: "Australian licensed operator"
    },
    playup: {
        regions: ["oceania", "africa", "asia", "north-america", "south-america", "europe"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "american-samoa",
            "belgium",
            "brazil",
            "canada",
            "china",
            "czech-republic",
            "denmark",
            "curacao",
            "sint-maarten",
            "france",
            "guyana",
            "french-guiana",
            "french-polynesia",
            "saint-pierre-and-miquelon",
            "reunion",
            "germany",
            "hong-kong",
            "hungary",
            "india",
            "indonesia",
            "iran",
            "ireland",
            "italy",
            "luxembourg",
            "malta",
            "netherlands",
            "new-zealand",
            "north-korea",
            "pakistan",
            "poland",
            "portugal",
            "russia",
            "singapore",
            "south-korea",
            "spain",
            "taiwan",
            "turkey",
            "united-arab-emirates",
            "united-states",
            "us-virgin-islands",
            "vietnam"
        ],
        confidence: "medium",
        notes: "Australian licensed operator with international presence."
    },
    matchbook: {
        regions: ["oceania", "africa", "asia", "north-america", "south-america", "europe"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "afghanistan",
            "armenia",
            "austria",
            "belarus",
            "belgium",
            "moldova",
            "montenegro",
            "netherlands",
            "slovakia",
            "switzerland",
            "turkey",
            "ukraine"
        ],
        confidence: "medium",
        notes: "International exchange, with a few restricted jurisdictions."
    },
    "1xbet": {
        regions: ["oceania", "africa", "asia", "north-america", "south-america", "europe"],
        mode: "unknown",
        confidence: "low",
        notes: "Offshore international bookmaker, availability and legality varies by jurisdiction."
    },
    marathonbet: {
        regions: ["oceania", "africa", "asia", "north-america", "south-america", "europe"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "united-states",
            "netherlands",
            "france",
            "curacao",
            "sint-maarten"
        ],
        confidence: "low",
        notes: "International bookmaker with worldwide availability. Reserves the right to prohibit registrations/bets from other jurisdictions as they deem necessary."
    },
    pinnacle: {
        regions: ["oceania", "africa", "asia", "north-america", "south-america", "europe"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "united-states",
            "american-samoa",
            "guam",
            "northern-mariana-islands",
            "puerto-rico",
            "us-virgin-islands",
            "france",
            "french-guiana",
            "french-polynesia",
            "guadeloupe",
            "martinique",
            "mayotte",
            "new-caledonia",
            "reunion",
            "saint-barthelemy",
            "saint-martin",
            "saint-pierre-and-miquelon",
            "wallis-and-futuna",
            "united-kingdom",
            "netherlands",
            "curacao",
            "aruba",
            "sint-maarten",
            "spain",
            "germany",
            "singapore",
            "north-korea",
            "denmark",
            "philippines",
            "syria",
            "turkey",
            "poland",
            "ireland",
            "czech-republic",
            "sudan",
            "australia",
            "norfolk-island",
            "christmas-island",
            "cocos-islands",
            "italy",
            "iran",
            "slovenia",
            "sweden",
            "portugal",
            "belgium",
            "hungary",
            "austria",
            "bulgaria",
            "greece",
            "lithuania",
            "romania",
            "cyprus",
            "canada",
            "serbia",
            "norway",
            "myanmar",
            "haiti",
            "somalia",
            "libya",
            "russia",
            "belarus",
            "venezuela",
            "brazil",
            "ukraine",
            "armenia",
            "azerbaijan",
            "georgia",
            "kazakhstan",
            "kyrgyzstan",
            "moldova",
            "tajikistan",
            "turkmenistan",
            "uzbekistan"
        ],
        confidence: "medium",
        notes: "Pinnacle is available globally except for the listed restricted countries and any other jurisdiction where gambling is illegal."
    },
    betonline: {
        regions: ["oceania", "africa", "asia", "north-america", "south-america", "europe"],
        mode: "unknown",
        confidence: "low",
        notes: "Offshore international bookmaker, availability and legality varies by jurisdiction."
    },
    coolbet: {
        regions: ["oceania", "africa", "asia", "north-america", "south-america", "europe"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "afghanistan",
            "albania",
            "algeria",
            "american-samoa",
            "angola",
            "antigua-and-barbuda",
            "argentina",
            "armenia",
            "aruba",
            "australia",
            "austria",
            "azerbaijan",
            "bahamas",
            "bahrain",
            "bangladesh",
            "barbados",
            "belarus",
            "belgium",
            "belize",
            "benin",
            "bhutan",
            "bolivia",
            "bosnia-and-hercegovina",
            "botswana",
            "brazil",
            "brunei",
            "bulgaria",
            "burkina-faso",
            "burundi",
            "cape-verde",
            "canada",
            "cambodia",
            "cayman-islands",
            "central-african-republic",
            "china",
            "christmas-island",
            "cocos-islands",
            "colombia",
            "comoros",
            "cook-islands",
            "costa-rica",
            "ivory-coast",
            "croatia",
            "cuba",
            "curacao",
            "cyprus",
            "czech-republic",
            "democratic-republic-of-the-congo",
            "denmark",
            "dominica",
            "dominican-republic",
            "egypt",
            "el-salvador",
            "equatorial-guinea",
            "eritrea",
            "ethiopia",
            "fiji",
            "france",
            "french-guiana",
            "french-polynesia",
            "saint-pierre-and-miquelon",
            "reunion",
            "georgia",
            "germany",
            "ghana",
            "gibraltar",
            "greece",
            "greenland",
            "grenada",
            "guadeloupe",
            "guam",
            "guatemala",
            "guinea",
            "guinea-bissau",
            "guyana",
            "haiti",
            "hong-kong",
            "hungary",
            "india",
            "indonesia",
            "iran",
            "iraq",
            "isle-of-man",
            "israel",
            "italy",
            "jamaica",
            "jersey",
            "jordan",
            "kazakhstan",
            "kenya",
            "south-korea",
            "north-korea",
            "kuwait",
            "kyrgyzstan",
            "laos",
            "latvia",
            "lebanon",
            "lesotho",
            "liberia",
            "libya",
            "liechtenstein",
            "lithuania",
            "luxembourg",
            "macau",
            "north-macedonia",
            "malaysia",
            "maldives",
            "mali",
            "marshall-islands",
            "martinique",
            "mauritania",
            "mauritius",
            "moldova",
            "monaco",
            "mongolia",
            "montenegro",
            "morocco",
            "mozambique",
            "myanmar",
            "namibia",
            "nauru",
            "netherlands",
            "nicaragua",
            "nigeria",
            "niue",
            "northern-mariana-islands",
            "oman",
            "pakistan",
            "palestine",
            "panama",
            "papua-new-guinea",
            "paraguay",
            "philippines",
            "poland",
            "portugal",
            "puerto-rico",
            "qatar",
            "congo-brazzaville",
            "romania",
            "russia",
            "saint-barthelemy", 
            "saint-kitts-and-nevis", 
            "saint-martin", 
            "saint-pierre-and-miquelon", 
            "san-marino",
            "saudi-arabia",
            "senegal",
            "serbia",
            "seychelles",
            "sierra-leone",
            "singapore",
            "sint-maarten",
            "slovakia",
            "slovenia",
            "somalia",
            "south-africa",
            "south-sudan",
            "spain",
            "sri-lanka",
            "sudan",
            "suriname",
            "swaziland",
            "switzerland",
            "syria",
            "taiwan",
            "tajikistan",
            "tanzania",
            "thailand",
            "east-timor",
            "trinidad-and-tobago", 
            "tunisia",
            "turkey",
            "turkmenistan",
            "uganda",
            "ukraine",
            "united-arab-emirates",
            "united-kingdom",
            "united-states",
            "uruguay", 
            "uzbekistan", 
            "vanuatu", 
            "vatican",
            "venezuela",
            "vietnam",
            "british-virgin-islands",
            "wallis-and-futuna", 
            "western-sahara",
            "yemen",
            "zimbabwe"
        ],
        confidence: "medium",
        notes: "Coolbet is an estonia based bookmaker available in other countries around the world."
    },
    betsson: {
        regions: ["europe", "south-america", "north-america", "africa"],
        mode: "locally_licensed",
        licensedCountries: [
            "argentina",
            "cameroon",
            "chile",
            "colombia",
            "denmark",
            "estonia",
            "greece",
            "iceland",
            "latvia",
            "lithuania",
            "mexico",
            "paraguay",
            "peru",
            "serbia",
            "spain",
            "sweden"
        ],
        confidence: "medium",
        notes: "Betsson is an international brand with licenses in multiple countries."
    },
    nordicbet: {
        regions: ["oceania", "africa", "asia", "north-america", "south-america", "europe"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "afghanistan",
            "albania",
            "andorra",
            "angola",
            "argentina",
            "armenia",
            "australia",
            "austria",
            "azerbaijan",
            "bahrain",
            "belarus",
            "belgium",
            "bosnia-and-hercegovina",
            "botswana",
            "brazil",
            "bulgaria",
            "burkina-faso",
            "burundi",
            "cambodia",
            "cameroon",
            "cayman-islands",
            "central-african-republic",
            "canada",
            "china",
            "colombia",
            "croatia",
            "cuba",
            "cyprus",
            "czech-republic",
            "democratic-republic-of-the-congo",
            "denmark",
            "eritrea",
            "estonia",
            "ethiopia",
            "faroe-islands",
            "france",
            "georgia",
            "germany",
            "gibraltar",
            "greece",
            "greenland",
            "guinea",
            "guinea-bissau",
            "haiti",
            "hong-kong",
            "hungary",
            "india",
            "indonesia",
            "iran",
            "iraq",
            "israel",
            "italy",
            "jamaica",
            "japan",
            "jordan",
            "kenya",
            "kuwait",
            "latvia",
            "lebanon",
            "libya",
            "lithuania",
            "luxembourg",
            "malaysia",
            "mali",
            "mauritania",
            "mauritius",
            "mexico",
            "moldova",
            "montenegro",
            "morocco",
            "myanmar",
            "netherlands",
            "nicaragua",
            "nigeria",
            "norfolk-island",
            "north-korea",
            "norway",
            "oman",
            "pakistan",
            "palau",
            "panama",
            "paraguay",
            "peru",
            "philippines",
            "poland",
            "portugal",
            "qatar",
            "romania",
            "russia",
            "rwanda",
            "saudi-arabia",
            "senegal",
            "serbia",
            "singapore",
            "slovakia",
            "slovenia",
            "somalia",
            "south-africa",
            "south-korea", 
            "south-sudan",
            "spain",
            "sudan",
            "switzerland",
            "syria",
            "taiwan",
            "tunisia",
            "turkey",
            "united-arab-emirates",
            "uganda",
            "ukraine",
            "united-kingdom",
            "vatican",
            "venezuela",
            "vietnam",
            "yemen",
            "zimbabwe",
            "united-states",
            "american-samoa",
            "guam",
            "marshall-islands",
            "northern-mariana-islands",
            "puerto-rico",
            "us-virgin-islands"
        ],
        confidence: "medium",
        notes: "Nordicbet is a licensed bookmaker primarily focused on the northern european markets."
    },
    leovegas: {
        regions: ["oceania", "africa", "asia", "north-america", "south-america", "europe"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "afghanistan",
            "curacao",
            "cyprus",
            "ethiopia",
            "iran",
            "iraq",
            "kuwait",
            "somalia",
            "syria",
            "united-states",
            "american-samoa",
            "guam",
            "northern-mariana-islands",
            "puerto-rico",
            "us-virgin-islands",
            "yemen"
        ],
        confidence: "medium",
        notes: "Leovegas is an international bookmaker licensed in several countries, notably prohibited in the U.S."
    },
    codere: {
        regions: ["europe", "north-america", "south-america"],
        mode: "locally_licensed",
        licensedCountries: [
            "spain",
            "italy",
            "argentina",
            "colombia",
            "mexico",
            "panama",
            "uruguay"
        ],
        confidence: "high",
        notes: "Codere is a bookmaker operating in multiple markets in Latin America and Europe."
    },
    tipico: {
        regions: ["europe"],
        mode: "locally_licensed",
        licensedCountries: [
            "germany",
            "austria"
        ],
        confidence: "high",
        notes: "Tipico is a European bookmaker with licences in Germany and Austria."
    },
    winamax: {
        regions: ["europe", "north-america", "south-america", "asia", "africa"],
        mode: "locally_licensed",
        licensedCountries: [
            "albania",
            "andorra",
            "belarus",
            "bosnia-and-hercegovina",
            "spain",
            "iceland",
            "north-macedonia",
            "moldova",
            "liechtenstein",
            "luxembourg",
            "malta",
            "norway",
            "serbia",
            "slovenia",
            "turkey",
            "argentina",
            "bahamas",
            "brazil",
            "dominican-republic",
            "canada",
            "costa-rica",
            "cuba",
            "mexico",
            "panama",
            "paraguay",
            "peru",
            "el-salvador",
            "uruguay",
            "chile",
            "ecuador",
            "armenia",
            "azerbaijan",
            "indonesia",
            "vietnam",
            "georgia",
            "israel",
            "cambodia",
            "kazakhstan",
            "kyrgyzstan",
            "mongolia",
            "malaysia",
            "maldives",
            "nepal",
            "united-arab-emirates",
            "singapore",
            "egypt",
            "madagascar",
            "morocco",
            "south-africa",
            "france",
            "finland",
            "croatia",
            "montenegro",
            "sweden",
            "thailand",
            "tajikistan",
            "turkmenistan",
            "philippines",
            "sri-lanka",
            "uzbekistan",
            "south-korea"
        ],
        confidence: "low",
        notes: "Winamax is an international bookmaker based in France. "
    },
    betclic: {
        regions: ["europe", "africa"],
        mode: "locally_licensed",
        licensedCountries: [
            "france",
            "french-guiana",
            "french-polynesia",
            "guadeloupe",
            "martinique",
            "mayotte",
            "new-caledonia",
            "reunion",
            "saint-barthelemy",
            "saint-martin",
            "saint-pierre-and-miquelon",
            "wallis-and-futuna",
            "portugal",
            "poland",
            "malta",
            "ivory-coast"
        ],
        confidence: "high",
        notes: "Betclic has operating locations in 5 countries in Europe and Africa."
    },
    mybookie: {
        regions: ["europe", "africa", "south-america", "north-america", "oceania", "asia"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "afghanistan",
            "albania",
            "algeria",
            "anguilla",
            "antigua-and-barbuda",
            "aruba",
            "armenia",
            "austria",
            "azerbaijan",
            "bahrain",
            "bangladesh",
            "belarus",
            "belgium",
            "bhutan",
            "brunei",
            "bulgaria",
            "burkina-faso",
            "burundi",
            "cambodia",
            "cayman-islands",
            "central-african-republic",
            "china",
            "comoros",
            "costa-rica",
            "cuba",
            "curacao",
            "cyprus",
            "czech-republic",
            "north-korea",
            "denmark",
            "djibouti",
            "dominican-republic",
            "united-kingdom",
            "eritrea",
            "estonia",
            "ethiopia",
            "fiji",
            "finland",
            "france",
            "gambia",
            "gibraltar",
            "greece",
            "guadeloupe",
            "guernsey",
            "guinea-bissau",
            "vatican",
            "hungary",
            "india",
            "indonesia",
            "iran",
            "iraq",
            "ireland",
            "isle-of-man",
            "israel",
            "jersey",
            "kazakhstan",
            "kyrgyzstan",
            "latvia",
            "lebanon",
            "liberia",
            "libya",
            "maldives",
            "mali",
            "malta",
            "martinique",
            "mauritania",
            "mauritius",
            "mayotte",
            "montenegro",
            "montserrat",
            "morocco",
            "nauru",
            "nepal",
            "netherlands",
            "new-caledonia",
            "papua-new-guinea",
            "niger",
            "ireland",
            "oman",
            "pakistan",
            "palestine",
            "pitcairn-islands",
            "poland",
            "kyrgyzstan",
            "reunion",
            "romania",
            "russia",
            "rwanda",
            "saint-helena",
            "saint-pierre-and-miquelon",
            "sao-tome-and-principe",
            "saudi-arabia",
            "serbia",
            "seychelles",
            "sierra-leone",
            "somalia",
            "south-sudan",
            "spain",
            "sudan",
            "svalbard-and-jan-mayen",
            "syria",
            "tajikistan",
            "democratic-republic-of-the-congo",
            "turkey",
            "turkmenistan",
            "tuvalu",
            "uganda",
            "ukraine",
            "united-arab-emirates",
            "uzbekistan",
            "vanuatu",
            "vietnam",
            "wallis-and-futuna",
            "yemen"
        ],
        confidence: "low",
        notes: "Mybookie is a primarily U.S facing offshore bookie legal in most states."
    },
    pmu: {
        regions: ["europe"],
        mode: "locally_licensed",
        licensedCountries: [
            "france",
            "french-guiana",
            "french-polynesia",
            "guadeloupe",
            "martinique",
            "mayotte",
            "new-caledonia",
            "reunion",
            "saint-barthelemy",
            "saint-martin",
            "saint-pierre-and-miquelon",
            "wallis-and-futuna"
        ],
        confidence: "high",
        notes: "PMU is a licensed french bookmaker."
    },
    "888sport": {
        regions: ["europe", "north-america"],
        mode: "locally_licensed",
        licensedCountries: [
            "united-kingdom",
            "gibraltar",
            "ireland",
            "jersey",
            "germany",
            "romania",
            "spain",
            "italy",
            "denmark",
            "malta",
            "sweden",
            "portugal",
            "canada",
            "united-states"
        ],
        confidence: "high",
        notes: "888Sport is licensed in many european countries as well as canada and some U.S states."
    },
    "william-hill": {
        regions: ["europe", "asia"],
        mode: "locally_licensed",
        licensedCountries: [
            "austria",
            "armenia",
            "germany",
            "italy",
            "hungary",
            "lithuania",
            "macau",
            "slovenia",
            "spain",
            "ukraine",
            "united-kingdom"
        ],
        confidence: "medium",
        notes: "William Hill is a UK bookmaker with some international presence."
    },
    everygame: {
        regions: ["africa", "europe", "asia", "north-america", "south-america", "oceania"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "australia",
            "austria",
            "germany",
            "united-kingdom",
            "france",
            "slovakia",
            "united-states",
            "anguilla",
            "bermuda",
            "british-indian-ocean-territory",
            "british-virgin-islands",
            "cayman-islands",
            "falkland-islands",
            "gibraltar",
            "montserrat",
            "pitcairn-islands",
            "saint-helena",
            "turks-and-caicos-islands",
            "isle-of-man",
            "jersey",
            "guernsey",
            "french-guiana",
            "french-polynesia",
            "guadeloupe",
            "martinique",
            "mayotte",
            "new-caledonia",
            "reunion",
            "saint-barthelemy",
            "saint-martin",
            "saint-pierre-and-miquelon",
            "wallis-and-futuna",
            "american-samoa",
            "guam",
            "northern-mariana-islands",
            "puerto-rico",
            "us-virgin-islands"
        ],
        confidence: "low",
        notes: "Everygame is an offshore bookmaker licensed in Curacao with global presence except for a few listed restricted countries."
    },
    netbet: {
        regions: ["africa", "asia", "europe", "north-america", "south-america", "oceania"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "afghanistan", 
            "albania", 
            "algeria", 
            "american-samoa", 
            "anguilla",
            "angola",
            "aruba",
            "australia",
            "bahamas",
            "barbados",
            "belgium",
            "benin",
            "botswana",
            "bulgaria",
            "burkina-faso",
            "cambodia",
            "cayman-islands",
            "china",
            "democratic-republic-of-the-congo",
            "congo-brazzaville",
            "ivory-coast",
            "croatia",
            "curacao",
            "denmark",
            "estonia",
            "ethiopia",
            "france",
            "french-polynesia",
            "french-guiana",
            "germany",
            "ghana",
            "greece",
            "guadeloupe",
            "guam",
            "guyana",
            "haiti",
            "hong-kong",
            "hungary",
            "iran",
            "iraq",
            "isle-of-man",
            "israel",
            "italy",
            "jamaica",
            "kazakhstan",
            "kenya",
            "laos",
            "latvia",
            "lithuania",
            "macau",
            "malta",
            "martinique",
            "mauritius",
            "mayotte",
            "mexico",
            "mongolia",
            "morocco",
            "mozambique",
            "myanmar",
            "nicaragua",
            "netherlands",
            "sint-maarten",
            "aruba",
            "curacao",
            "nigeria",
            "northern-mariana-islands",
            "new-caledonia",
            "north-korea",
            "philippines",
            "marshall-islands",
            "micronesia",
            "palau",
            "northern-mariana-islands",
            "pakistan",
            "portugal",
            "puerto-rico",
            "reunion",
            "romania",
            "russia",
            "saint-barthelemy",
            "saint-pierre-and-miquelon",
            "senegal",
            "sierra-leone",
            "singapore",
            "slovakia",
            "south-sudan",
            "spain",
            "switzerland",
            "syria",
            "thailand",
            "trinidad-and-tobago",
            "turkey",
            "united-states",
            "us-virgin-islands",
            "united-kingdom",
            "uganda",
            "vanuatu",
            "venezuela",
            "vietnam",
            "wallis-and-futuna",
            "yemen",
            "zimbabwe"
        ],
        confidence: "medium",
        notes: "Netbet is an offshore bookmaker with a license from the Malta Gaming Authority and is available worldwide except for listed restricted jurisdictions."
    },
    atg: {
        regions: ["europe"],
        mode: "locally_licensed",
        licensedCountries: ["sweden"],
        confidence: "high",
        notes: "Sweden-focused licensed operator.",
    },
    "svenska-spel": {
        regions: ["europe"],
        mode: "locally_licensed",
        licensedCountries: ["sweden"],
        confidence: "high",
        notes: "State-owned swedish licensed operator."
    },
    campobet: {
        regions: ["europe", "north-america"],
        mode: "locally_licensed",
        licensedCountries: [
            "sweden",
            "denmark",
            "mexico"
        ],
        confidence: "medium",
        notes: "Campobet is a bookmaker registered in Malta with a license in Mexico."
    },
    hajper: {
        regions: ["europe"],
        mode: "locally_licensed",
        licensedCountries: [
            "sweden"
        ],
        confidence: "high",
        notes: "Hajper is a swedish licensed and regulated bookmaker."
    },
    "mr-green": {
        regions: ["africa", "europe", "asia", "north-america", "south-america", "oceania"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "afghanistan",
            "australia",
            "bosnia-and-hercegovina",
            "myanmar",
            "cuba",
            "democratic-republic-of-the-congo",
            "iran",
            "iraq",
            "libya",
            "north-korea",
            "serbia",
            "sudan",
            "syria",
            "united-states",
            "zimbabwe",
            "american-samoa",
            "guam",
            "northern-mariana-islands",
            "puerto-rico",
            "us-virgin-islands"
        ],
        confidence: "medium",
        notes: "Mr Green is a global bookmaker licensed by the Malta Gaming Authority."
    },
    smarkets: {
        regions: ["africa", "asia", "europe", "north-america", "south-america", "oceania"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "australia",
            "france",
            "hong-kong",
            "switzerland",
            "china",
            "south-africa",
            "denmark",
            "czech-republic",
            "belgium",
            "turkey",
            "united-states",
            "italy",
            "portugal",
            "russia",
            "belarus",
            "ukraine",
            "kazakhstan",
            "norway",
            "netherlands",
            "christmas-island",
            "cocos-islands",
            "norfolk-island",
            "french-guiana",
            "french-polynesia",
            "guadeloupe",
            "martinique",
            "mayotte",
            "new-caledonia",
            "reunion",
            "saint-barthelemy",
            "saint-martin",
            "saint-pierre-and-miquelon",
            "wallis-and-futuna",
            "american-samoa",
            "guam",
            "northern-mariana-islands",
            "puerto-rico",
            "us-virgin-islands",
            "sint-maarten",
            "aruba",
            "curacao"
        ],
        confidence: "medium",
        notes: "Smarkets is an international exchange available in many countries."
    },
    casumo: {
        regions: ["europe", "north-america", "oceania"],
        mode: "locally_licensed",
        licensedCountries: [
            "finland",
            "sweden",
            "united-kingdom",
            "canada",
            "new-zealand",
            "ireland",
            "gibraltar"
        ],
        confidence: "medium",
        notes: "Casumo is a Malta registered bookmaker operating in Europe and some other countries worldwide."
    },
    "grosvenor-casinos": {
        regions: ["europe"],
        mode: "locally_licensed",
        licensedCountries: [
            "united-kingdom",
            "ireland",
            "guernsey",
            "jersey",
            "gibraltar",
            "isle-of-man"
        ],
        confidence: "high",
        notes: "Grosvenor is a UK licensed bookmaker, also licensed by the government of Gibraltar."
    },
    betfred: {
        regions: ["europe"],
        mode: "locally_licensed",
        licensedCountries: [
            "united-kingdom",
            "ireland",
            "gibraltar"
        ],
        confidence: "high",
        notes: "Betfred is a UK bookmaker licensed by the Gambling Commission of Great Britain and by the Government of Gibraltar."
    },
    coral: {
        regions: ["europe"],
        mode: "locally_licensed",
        licensedCountries: [
            "united-kingdom",
            "gibraltar",
            "jersey",
            "ireland"
        ],
        confidence: "high",
        notes: "Coral is a UK bookmaker licensed in both the UK and Gibraltar."
    },
    betway: {
        regions: ["africa", "asia", "europe", "north-america", "south-america", "oceania"],
        mode: "locally_licensed",
        licensedCountries: [
            "united-kingdom",
            "canada",
            "malta",
            "italy",
            "denmark",
            "spain",
            "belgium",
            "germany",
            "mexico",
            "south-africa",
            "portugal",
            "ireland",
            "poland",
            "france",
            "argentina",
            "nigeria",
            "ghana",
            "united-states"
        ],
        confidence: "medium",
        notes: "Betway is a UK bookmaker that holds gambling licenses in many countries worldwide."
    },
    "paddy-power": {
        regions: ["europe"],
        mode: "locally_licensed",
        licensedCountries: [
            "united-kingdom",
            "ireland",
            "gibraltar",
            "malta"
        ],
        confidence: "high",
        notes: "Paddypower is a UK licensed and regulated bookmaker."
    },
    betvictor: {
        regions: ["europe", "asia", "south-america", "north-america", "oceania", "africa"],
        mode: "locally_licensed",
        licensedCountries: [
            "aruba",
            "bahrain",
            "bermuda",
            "brunei",
            "canada",
            "chile",
            "finland",
            "falkland-islands",
            "united-kingdom",
            "georgia",
            "guernsey",
            "gibraltar",
            "greenland",
            "ireland",
            "isle-of-man",
            "british-indian-ocean-territory",
            "jersey",
            "jordan",
            "kuwait",
            "lebanon",
            "liechtenstein",
            "luxembourg",
            "montenegro",
            "marshall-islands",
            "mali",
            "new-zealand",
            "oman",
            "qatar",
            "saudi-arabia",
            "seychelles",
            "swaziland",
            "trinidad-and-tobago",
            "british-virgin-islands"
        ],
        confidence: "high",
        notes: "Betvictor is an international bookmaker licensed in Gibraltar, the UK and Ontario."
    },
    skybet: {
        regions: ["europe"],
        mode: "locally_licensed",
        licensedCountries: [
            "united-kingdom",
            "ireland",
            "gibraltar",
            "isle-of-man",
            "jersey",
            "guernsey"
        ],
        confidence: "high",
        notes: "Skybet is a UK regulated bookmaker operating within the UK and Ireland."
    },
    boylesports: {
        regions: ["europe"],
        mode: "locally_licensed",
        licensedCountries: [
            "united-kingdom",
            "ireland",
            "gibraltar"
        ],
        confidence: "high",
        notes: "Boylesports is a UK regulated bookmaker also available in Ireland and Gibraltar."
    },
    "virgin-bet": {
        regions: ["europe"],
        mode: "locally_licensed",
        licensedCountries: [
            "united-kingdom",
        ],
        confidence: "high",
        notes: "Virgin Bet is a UK regulated bookmaker currently only available in the United Kingdom."
    },
    livescorebet: {
        regions: ["europe", "africa"],
        mode: "locally_licensed",
        licensedCountries: [
            "united-kingdom",
            "gibraltar",
            "nigeria",
            "bulgaria"
        ],
        confidence: "high",
        notes: "Livescorebet is a UK licensed bookmaker available in a few other countries around the world."
    },
    lowvig: {
        regions: ["africa", "asia", "europe", "north-america", "south-america", "oceania"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "australia",
            "afghanistan",
            "belgium",
            "bulgaria",
            "central-african-republic",
            "democratic-republic-of-the-congo",
            "eritrea",
            "france",
            "guinea-bissau",
            "iran",
            "iraq",
            "lebanon",
            "libya",
            "mali",
            "malta",
            "north-korea",
            "panama",
            "somalia",
            "south-sudan",
            "sudan",
            "yemen"
        ],
        confidence: "high",
        notes: "Lowvig is a licensed offshore bookmaker operating internationally except for a few restricted countries."
    },
    draftkings: {
        regions: ["north-america"],
        mode: "locally_licensed",
        licensedCountries: [
            "united-states"
        ],
        confidence: "high",
        notes: "Draftkings is a US regulated bookmaker available in many states."
    },
    bovada: {
        regions: ["north-america"],
        mode: "locally_licensed",
        licensedCountries: [
            "united-states"
        ],
        confidence: "high",
        notes: "Bovada is a US based bookmaker available in many US states."
    },
    betus: {
        regions: ["africa", "asia", "europe", "north-america", "south-america", "oceania"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "belgium",
            "costa-rica",
            "croatia",
            "curacao",
            "france",
            "germany",
            "india",
            "iran",
            "netherlands",
            "sint-maarten",
            "aruba",
            "curacao",
            "panama",
            "philippines",
            "romania",
            "slovenia",
            "united-kingdom"
        ],
        confidence: "medium",
        notes: "BetUS is an offshore international bookmaker which accepts U.S. players from many states."
    },
    betrivers: {
        regions: ["north-america"],
        mode: "locally_licensed",
        licensedCountries: [
            "united-states",
            "canada"
        ],
        confidence: "high",
        notes: "BetRivers is a US based bookmaker with licenses in many U.S. states in addition to Ontario, Canada."
    },
    betmgm: {
        regions: ["north-america", "europe"],
        mode: "locally_licensed",
        licensedCountries: [
            "united-states",
            "canada",
            "united-kingdom",
            "netherlands",
            "sweden"
        ],
        confidence: "high",
        notes: "BetMGM is a bookmaker licensed in numerous countries, including many U.S. states."
    },
    fanduel: {
        regions: ["north-america"],
        mode: "locally_licensed",
        licensedCountries: [
            "united-states"
        ],
        confidence: "high",
        notes: "Fanduel is a U.S. based sportsbook licensed in many U.S. states."
    },
    "hard-rock-bet": {
        regions: ["north-america"],
        mode: "locally_licensed",
        licensedCountries: [
            "united-states"
        ],
        confidence: "high",
        notes: "Hard Rock Bet is a U.S. based sportsbook available in a few U.S. states."
    },
    "bally-bet": {
        regions: ["north-america"],
        mode: "locally_licensed",
        licensedCountries: [
            "united-states"
        ],
        confidence: "high",
        notes: "Bally Bet is a US bookmaker available in 10+ U.S. states."
    },
    betparx: {
        regions: ["north-america"],
        mode: "locally_licensed",
        licensedCountries: [
            "united-states"
        ],
        confidence: "high",
        notes: "BetPARX is a U.S. bookmaker available in 4+ U.S. states."
    },
    thescore: {
        regions: ["north-america"],
        mode: "locally_licensed",
        licensedCountries: [
            "united-states",
            "canada"
        ],
        confidence: "high",
        notes: "TheScore Bet is a U.S. sportsbook available in 20+ U.S. states and Ontario."
    },
    stake: {
        regions: ["africa", "asia", "europe", "north-america", "south-america", "oceania"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "afghanistan",
            "argentina",
            "austria",
            "australia",
            "belgium",
            "brazil",
            "cayman-islands",
            "colombia",
            "croatia",
            "cuba",
            "curacao",
            "czech-republic",
            "cyprus",
            "democratic-republic-of-the-congo",
            "denmark",
            "france",
            "germany",
            "greece",
            "iran",
            "iraq",
            "israel",
            "italy",
            "liberia",
            "libya",
            "lithuania",
            "malta",
            "netherlands",
            "north-korea",
            "canada",
            "peru",
            "poland",
            "portugal",
            "serbia",
            "slovakia",
            "south-africa",
            "south-sudan",
            "spain",
            "sudan",
            "syria",
            "sweden",
            "switzerland",
            "united-kingdom",
            "united-states",
            "zimbabwe"
        ],
        confidence: "medium",
        notes: "Stake is an international crypto bookmaker available in most countries around the world."
    },
    "22bet": {
        regions: ["africa", "asia", "europe", "north-america", "south-america", "oceania"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "afghanistan",
            "albania",
            "algeria",
            "angola",
            "australia",
            "bahamas",
            "botswana",
            "belgium",
            "bulgaria",
            "colombia",
            "croatia",
            "czech-republic",
            "denmark",
            "estonia",
            "ecuador",
            "ethiopia",
            "france",
            "ghana",
            "guyana",
            "hong-kong",
            "italy",
            "iran",
            "iraq",
            "israel",
            "kuwait",
            "latvia",
            "lithuania",
            "mexico",
            "namibia",
            "nicaragua",
            "north-korea",
            "pakistan",
            "panama",
            "philippines",
            "portugal",
            "romania",
            "singapore",
            "spain",
            "sweden",
            "switzerland",
            "sudan",
            "syria",
            "taiwan",
            "trinidad-and-tobago",
            "tunisia",
            "uganda",
            "united-kingdom",
            "united-states",
            "yemen",
            "zimbabwe"
        ],
        confidence: "medium",
        notes: "22Bet is an offshore licensed bookmaker available in many countries across the world."
    },
    "20bet": {
        regions: ["africa", "asia", "europe", "north-america", "south-america", "oceania"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "belarus", 
            "ukraine", 
            "curacao", 
            "cyprus", 
            "estonia", 
            "france", 
            "french-guiana", 
            "french-polynesia", 
            "gibraltar", 
            "guadeloupe", 
            "israel", 
            "jersey", 
            "latvia", 
            "lithuania", 
            "malta", 
            "netherlands", 
            "russia", 
            "united-kingdom", 
            "united-arab-emirates", 
            "belgium", 
            "united-states", 
            "angola", 
            "albania", 
            "iraq", 
            "jamaica", 
            "uganda", 
            "montserrat", 
            "iran", 
            "lebanon", 
            "zimbabwe", 
            "mauritius", 
            "nicaragua", 
            "yemen", 
            "central-african-republic", 
            "ivory-coast", 
            "sudan", 
            "liberia", 
            "syria", 
            "cayman-islands", 
            "somalia", 
            "congo-brazzaville", 
            "north-korea", 
            "eritrea", 
            "haiti", 
            "sierra-leone", 
            "ethiopia", 
            "myanmar", 
            "south-sudan", 
            "burkina-faso", 
            "libya", 
            "mali", 
            "barbados", 
            "rwanda", 
            "australia", 
            "cuba", 
            "south-korea"
        ],
        confidence: "medium",
        notes: "20Bet is an international offshore bookmaker available in many countries."
    },
    melbet: {
        regions: ["africa", "asia", "north-america", "south-america"],
        mode: "locally_licensed",
        licensedCountries: [
            "kenya",
            "ghana",
            "egypt",
            "tanzania",
            "uganda",
            "nigeria",
            "ethiopia",
            "somalia",
            "india",
            "bangladesh",
            "pakistan",
            "nepal",
            "sri-lanka",
            "malaysia",
            "myanmar",
            "canada",
            "brazil",
            "argentina"
        ],
        confidence: "medium",
        notes: "Melbet is a Curacao licensed offshore bookmaker operating in many countries around the world."
    },
    betwinner: {
        regions: ["asia", "africa", "europe","south-america", "north-america", "oceania"],
        mode: "locally_licensed",
        licensedCountries: [
            "afghanistan", 
            "armenia",
            "azerbaijan",
            "bahrain",
            "bangladesh",
            "cambodia",
            "georgia",
            "india",
            "iran",
            "iraq",
            "palestine",
            "japan",
            "jordan",
            "kazakhstan",
            "kyrgyzstan",
            "malaysia",
            "mongolia",
            "nepal",
            "pakistan",
            "philippines",
            "saudi-arabia",
            "singapore",
            "sri-lanka",
            "thailand",
            "turkey",
            "united-arab-emirates",
            "uzbekistan",
            "vietnam",
            "albania",
            "gibraltar",
            "hungary",
            "kosovo",
            "moldova",
            "russia",
            "costa-rica",
            "dominican-republic", 
            "honduras",
            "mexico",
            "nicaragua",
            "saint-lucia",
            "argentina",
            "bolivia",
            "brazil",
            "chile",
            "colombia",
            "ecuador",
            "paraguay",
            "peru",
            "venezuela",
            "uruguay",
            "congo-brazzaville",
            "ghana",
            "kenya",
            "nigeria",
            "somalia",
            "south-africa",
            "tanzania",
            "togo",
            "uganda",
            "zambia",
            "zimbabwe",
            "new-zealand"
        ],
        confidence: "medium",
        notes: "Betwinner is an offshore bookmaker available in many countries, mainly across Asia, Africa and South America."
    },
    parimatch: {
        regions: ["africa", "asia", "europe", "north-america", "south-america", "oceania"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "aruba",
            "australia",
            "curacao",
            "france",
            "netherlands",
            "sint-maarten",
            "singapore",
            "spain",
            "united-kingdom",
            "united-states",
            "iran",
            "north-korea",
            "myanmar"
        ],
        confidence: "medium",
        notes: "Parimatch is an international offshore bookmaker available everywhere except for a few restricted jurisdictions."
    },
    dafabet: {
        regions: ["africa", "asia", "europe", "north-america", "south-america", "oceania"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "united-states",
            "american-samoa",
            "samoa",
            "us-virgin-islands",
            "puerto-rico",
            "united-kingdom",
            "france",
            "belgium",
            "netherlands",
            "ireland",
            "germany",
            "spain",
            "portugal",
            "italy",
            "switzerland",
            "cyprus",
            "czech-republic",
            "ukraine",
            "romania",
            "estonia",
            "bulgaria",
            "poland",
            "colombia",
            "aruba",
            "sint-maarten",
            "curacao",
            "israel",
            "turkey",
            "australia",
            "singapore",
            "hong-kong",
            "macau",
            "taiwan",
            "philippines"
        ],
        confidence: "medium",
        notes: "DafaBet is an international offshore bookmaker with presence all across the world."
    },
    "sportsbet-io": {
        regions: ["africa", "asia", "europe", "north-america", "south-america", "oceania"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "afghanistan",
            "algeria",
            "angola",
            "australia",
            "austria",
            "belgium",
            "brazil",
            "burundi",
            "central-african-republic",
            "curacao",
            "czech-republic",
            "ivory-coast",
            "north-korea",
            "democratic-republic-of-the-congo",
            "estonia",
            "france",
            "germany",
            "guernsey",
            "guinea",
            "guinea-bissau",
            "isle-of-man",
            "haiti",
            "iran",
            "jersey",
            "kenya",
            "laos",
            "libya",
            "mali",
            "malta",
            "myanmar",
            "namibia",
            "netherlands",
            "nicaragua",
            "niger",
            "russia",
            "somalia",
            "south-sudan",
            "spain",
            "sudan",
            "syria",
            "united-kingdom",
            "united-states",
            "british-virgin-islands",
            "yemen"
        ],
        confidence: "medium",
        notes: "Sportsbet.io is an offshore crypto bookmaker available in many countries."
    },
    cloudbet: {
        regions: ["africa", "asia", "europe", "north-america", "south-america", "oceania"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "australia",
            "austria",
            "belgium",
            "china",
            "macau",
            "hong-kong",
            "curacao",
            "cuba",
            "france",
            "germany",
            "iran",
            "lithuania",
            "malta",
            "myanmar",
            "netherlands",
            "north-korea",
            "singapore",
            "syria",
            "spain",
            "united-states",
            "us-virgin-islands",
            "guam",
            "puerto-rico",
            "american-samoa",
            "united-kingdom",
            "ukraine"
        ],
        confidence: "medium",
        notes: "Cloudbet is an offshore bookmaker licensed in Curacao which accepts crypto currency."
    },
    sbotop: {
        regions: ["asia", "south-america"],
        mode: "locally_licensed",
        licensedCountries: [
            "bangladesh",
            "brazil",
            "cambodia",
            "india",
            "indonesia",
            "laos",
            "malaysia",
            "myanmar",
            "south-korea",
            "thailand",
            "vietnam"
        ],
        confidence: "high",
        notes: "SBOTOP is an Asia facing bookmaker also available in Brazil. "
    },
    m88: {
        regions: ["africa", "asia", "europe", "north-america", "south-america", "oceania"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "philippines",
            "cambodia",
            "germany",
            "australia",
            "taiwan",
            "united-states",
            "singapore",
            "hong-kong",
            "united-kingdom",
            "france",
            "guadeloupe",
            "guyana",
            "martinique",
            "reunion"
        ],
        confidence: "medium",
        notes: "M88 is an international offshore sportsbook licensed in Vanuatu and available in most countries."
    },
    fun88: {
        regions: ["africa", "asia", "europe", "north-america", "south-america", "oceania"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "philippines",
            "germany",
            "united-states",
            "turkey",
            "singapore",
            "malaysia",
            "taiwan"
        ],
        confidence: "low",
        notes: "Fun88 is an international offshore bookmaker restricted in only a few countries."
    },
    novibet: {
        regions: ["europe", "oceania", "north-america", "south-america"],
        mode: "locally_licensed",
        licensedCountries: [
            "finland",
            "ireland",
            "greece",
            "cyprus",
            "new-zealand",
            "brazil",
            "chile",
            "ecuador",
            "mexico",
            "canada"
        ],
        confidence: "medium",
        notes: "Novibet is an international bookmaker available in select countries around the world."
    },
    stoiximan: {
        regions: ["europe"],
        mode: "locally_licensed",
        licensedCountries: [
            "cyprus"
        ],
        confidence: "high",
        notes: "Stoiximan is a greek bookmaker only available in Cyprus."
    },
    superbet: {
        regions: ["europe", "south-america"],
        mode: "locally_licensed",
        licensedCountries: [
            "romania",
            "poland",
            "belgium",
            "serbia",
            "croatia",
            "malta",
            "cyprus",
            "brazil"
        ],
        confidence: "medium",
        notes: "Superbet is a mainly European sportsbook that also has presence in Brazil."
    },
    "bet-at-home": {
        regions: ["africa", "asia", "europe", "north-america", "south-america", "oceania"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "france",
            "united-states",
            "turkey",
            "albania",
            "belgium",
            "spain",
            "portugal",
            "denmark",
            "czech-republic",
            "croatia",
            "romania",
            "bulgaria",
            "australia",
            "greece",
            "russia",
            "israel",
            "iraq",
            "iran",
            "syria",
            "afghanistan",
            "hungary",
            "united-kingdom",
            "north-korea",
            "sweden",
            "serbia",
            "bosnia-and-hercegovina",
            "slovakia",
            "poland",
            "netherlands",
            "montenegro",
            "gibraltar"
        ],
        confidence: "medium",
        notes: "Bet-at-home is a Malta licensed bookmaker available in many countries across the world."
    },
    interwetten: {
        regions: ["africa", "asia", "europe", "north-america", "south-america", "oceania"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "united-states",
            "australia",
            "turkey",
            "france",
            "poland",
            "belgium",
            "italy",
            "united-kingdom",
            "india",
            "cyprus",
            "indonesia",
            "brazil",
            "romania",
            "portugal",
            "hungary",
            "bulgaria",
            "denmark",
            "slovenia",
            "netherlands",
            "estonia",
            "lithuania",
            "latvia",
            "croatia",
            "czech-republic",
            "finland",
            "slovakia",
            "north-korea",
            "iran"
        ],
        confidence: "medium",
        notes: "Interwetten is a Malta licensed bookmaker available in most countries except restricted countries."
    },
    expekt: {
        regions: ["europe"],
        mode: "locally_licensed",
        licensedCountries: [
            "sweden",
            "denmark"
        ],
        confidence: "high",
        notes: "Expekt is a regional bookmaker only available in some northern European countries."
    },
    betsafe: {
        regions: ["africa", "asia", "europe", "north-america", "south-america", "oceania"],
        mode: "global_except_restricted",
        restrictedCountries: [
            "afghanistan",
            "albania",
            "algeria",
            "andorra",
            "angola",
            "argentina",
            "armenia",
            "australia",
            "azerbaijan",
            "bahrain",
            "belarus",
            "belgium",
            "bosnia-and-hercegovina",
            "botswana",
            "brazil",
            "bulgaria",
            "burkina-faso",
            "burundi",
            "cayman-islands",
            "central-african-republic",
            "colombia",
            "cyprus",
            "denmark",
            "democratic-republic-of-the-congo",
            "eritrea",
            "estonia",
            "ethiopia",
            "faroe-islands",
            "philippines",
            "united-arab-emirates",
            "france",
            "georgia",
            "gibraltar",
            "greece",
            "greenland",
            "guinea",
            "guinea-bissau",
            "haiti",
            "hong-kong",
            "india",
            "indonesia",
            "iraq",
            "iran",
            "israel",
            "italy",
            "jamaica",
            "japan",
            "yemen",
            "jordan",
            "cambodia",
            "cameroon",
            "kenya",
            "china",
            "croatia",
            "cuba",
            "kuwait",
            "latvia",
            "lebanon",
            "libya",
            "lithuania",
            "luxembourg",
            "malaysia",
            "mali",
            "morocco",
            "mauritania",
            "mauritius",
            "mexico",
            "moldova",
            "montenegro",
            "myanmar",
            "netherlands",
            "nicaragua",
            "nigeria",
            "north-korea",
            "norfolk-island",
            "norway",
            "oman",
            "canada",
            "austria",
            "pakistan",
            "palau",
            "panama",
            "paraguay",
            "poland",
            "portugal",
            "qatar",
            "romania",
            "rwanda",
            "russia",
            "saudi-arabia",
            "switzerland",
            "senegal",
            "serbia",
            "singapore",
            "slovakia",
            "slovenia",
            "somalia",
            "spain",
            "united-kingdom",
            "south-africa",
            "south-korea",
            "south-sudan",
            "syria",
            "taiwan",
            "czech-republic",
            "tunisia",
            "turkey",
            "germany",
            "uganda",
            "ukraine",
            "hungary",
            "vatican",
            "venezuela",
            "vietnam",
            "zimbabwe",
            "united-states",
            "marshall-islands",
            "guam",
            "american-samoa",
            "northern-mariana-islands",
            "puerto-rico",
            "us-virgin-islands"
        ],
        confidence: "medium",
        notes: "Betsafe is an international bookmaker licensed in Malta."
    }
};