export type Market = "all" | "us" | "uk" | "eu" | "fr" | "se" | "au";

export type RegionalBookmakerRow = {
  bookmaker_id: string;
  bookmaker_key?: string;
  bookmaker_title: string;
  market?: Exclude<Market, "all">;
  samples: number;
  average_margin_percent: number;
};

type RawRegionalBookmakerRow = Omit<RegionalBookmakerRow, "logo" | "url" | "backgroundColor">;

type BookmakerMeta = {
  logo: string;
  url: string;
  backgroundColor?: string;
};

const BOOKMAKER_META: Record<string, BookmakerMeta> = {
  "1xbet": { logo: "/logos/1xbet.svg", url: "https://1xbet.com", backgroundColor: "#ffffff" },
  "888sport": { logo: "/logos/888sport.svg", url: "https://www.888sport.com", backgroundColor: "#ffffff" },
  atg: { logo: "/logos/atg.svg", url: "https://www.atg.se", backgroundColor: "#0357a1" },
  ballybet: { logo: "/logos/ballybet.svg", url: "https://www.ballybet.com", backgroundColor: "#ed0000" },
  betfair: { logo: "/logos/betfair.svg", url: "https://www.betfair.com", backgroundColor: "#ffb60d" },
  betfair_sportsbook: { logo: "/logos/betfair.svg", url: "https://www.betfair.com/sport", backgroundColor: "#ffb60d" },
  betfred: { logo: "/logos/betfred.png", url: "https://www.betfred.com", backgroundColor: "#ffffff" },
  betmgm: { logo: "/logos/betmgm.svg", url: "https://sports.betmgm.com", backgroundColor: "#0a0a0a" },
  betonline: { logo: "/logos/betonline.svg", url: "https://www.betonline.ag", backgroundColor: "#2d2e2c" },
  betparx: { logo: "/logos/betparx.svg", url: "https://www.betparx.com", backgroundColor: "#1a0533" },
  betright: { logo: "/logos/betright.svg", url: "https://www.betright.com.au", backgroundColor: "#0f1729" },
  betsson: { logo: "/logos/betsson.svg", url: "https://www.betsson.com", backgroundColor: "#ff6600" },
  betus: { logo: "/logos/betus.svg", url: "https://www.betus.com.pa", backgroundColor: "#071226" },
  betvictor: { logo: "/logos/betvictor.svg", url: "https://www.betvictor.com", backgroundColor: "#1d262e" },
  betway: { logo: "/logos/betway.svg", url: "https://www.betway.com", backgroundColor: "#ffffff" },
  betr: { logo: "/logos/betr.svg", url: "https://www.betr.com.au", backgroundColor: "#083bd4"},
  betrivers: { logo: "/logos/betrivers.svg", url: "https://www.betrivers.com", backgroundColor: "#1d355c"},
  betclic: { logo: "/logos/betclic.svg", url: "https://www.betclic.com", backgroundColor: "#d1151e" },
  bovada: { logo: "/logos/bovada.svg", url: "https://www.bovada.lv", backgroundColor: "#ffffff" },
  boylesports: { logo: "/logos/boylesports.svg", url: "https://www.boylesports.com", backgroundColor: "#2500f5" },
  campobet: { logo: "/logos/campobet.svg", url: "https://www.campobet.com", backgroundColor: "#104a2d" },
  casumo: { logo: "/logos/casumo.svg", url: "https://www.casumo.com", backgroundColor: "#32007d" },
  codere: { logo: "/logos/codere.svg", url: "https://www.codere.com", backgroundColor: "#252a30" },
  coolbet: { logo: "/logos/coolbet.svg", url: "https://www.coolbet.com", backgroundColor: "#2b2b36" },
  coral: { logo: "/logos/coral.svg", url: "https://sports.coral.co.uk", backgroundColor: "#084d8c" },
  draftkings: { logo: "/logos/draftkings.png", url: "https://sportsbook.draftkings.com", backgroundColor: "#ffffff" },
  everygame: { logo: "/logos/everygame.svg", url: "https://www.everygame.eu", backgroundColor: "#0d0d0d" },
  fanduel: { logo: "/logos/fanduel.png", url: "https://sportsbook.fanduel.com", backgroundColor: "#ffffff" },
  grosvenor: { logo: "/logos/grosvenor.svg", url: "https://www.grosvenorcasinos.com", backgroundColor: "#080808" },
  gtbets: { logo: "/logos/gtbets.png", url: "https://www.gtbets.ag", backgroundColor: "#01133b" },
  hajper: { logo: "/logos/hajper.svg", url: "https://www.hajper.com", backgroundColor: "#0d194f" },
  hardrockbet: { logo: "/logos/hardrockbet.svg", url: "https://app.hardrock.bet", backgroundColor: "#1b191c" },
  ladbrokes: { logo: "/logos/ladbrokes.svg", url: "https://www.ladbrokes.com", backgroundColor: "#f01d27" }, 
  leovegas: { logo: "/logos/leovegas.svg", url: "https://www.leovegas.com", backgroundColor: "#ed4700" },
  livescorebet: { logo: "/logos/livescorebet.jpg", url: "https://www.livescorebet.com", backgroundColor: "#ffffff" },
  lowvig: { logo: "/logos/lowvig.svg", url: "https://www.lowvig.ag", backgroundColor: "#01153d" },
  marathonbet: { logo: "/logos/marathonbet.png", url: "https://www.marathonbet.com", backgroundColor: "#013d78" },
  matchbook: { logo: "/logos/matchbook.png", url: "https://www.matchbook.com", backgroundColor: "#e81e25" },
  mrgreen: { logo: "/logos/mrgreen.svg", url: "https://www.mrgreen.com", backgroundColor: "#015436" },
  mybookie: { logo: "/logos/mybookie.png", url: "https://www.mybookie.ag", backgroundColor: "#242526" },
  neds: { logo: "/logos/neds.svg", url: "https://www.neds.com.au", backgroundColor: "#f55d05" },
  netbet: { logo: "/logos/netbet.png", url: "https://www.netbet.fr", backgroundColor: "#363845" },
  nordicbet: { logo: "/logos/nordicbet.svg", url: "https://www.nordicbet.com", backgroundColor: "#0067b9" },
  paddypower: { logo: "/logos/paddypower.svg", url: "https://www.paddypower.com", backgroundColor: "ffffff" },
  pinnacle: { logo: "/logos/pinnacle.svg", url: "https://www.pinnacle.com", backgroundColor: "#09192e" },
  playup: { logo: "/logos/playup.svg", url: "https://www.playup.com.au", backgroundColor: "#191c21" },
  pmu: { logo: "/logos/pmu.png", url: "https://pmu.fr", backgroundColor: "ffffff" },
  pointsbet: { logo: "/logos/pointsbet.svg", url: "https://pointsbet.com", backgroundColor: "#0a0a0a" },
  skybet: { logo: "/logos/skybet.svg", url: "https://www.skybet.com", backgroundColor: "ffffff" },
  smarkets: { logo: "/logos/smarkets.svg", url: "https://smarkets.com", backgroundColor: "ffffff" },
  sportsbet: { logo: "/logos/sportsbet.jpg", url: "https://www.sportsbet.com.au", backgroundColor: "#0067ab" },
  svenskaspel: { logo: "/logos/svenskaspel.svg", url: "https://www.svenskaspel.se", backgroundColor: "#a10812" },
  tab: { logo: "/logos/tab.png", url: "https://www.tab.com.au", backgroundColor: "#ffffff" },
  tabtouch: { logo: "/logos/tabtouch.svg", url: "https://www.tabtouch.com.au", backgroundColor: "#522d6e" },
  thescorebet: { logo: "/logos/thescorebet.svg", url: "https://thescore.bet", backgroundColor: "#101d2e" },
  tipico: { logo: "/logos/tipico.svg", url: "https://www.tipico.com", backgroundColor: "#ffffff" },
  unibet: { logo: "/logos/unibet.png", url: "https://www.unibet.com", backgroundColor: "#147a45" },
  virginbet: { logo: "/logos/virginbet.jpeg", url: "https://www.virginbet.com", backgroundColor: "#cc080f" },
  "william-hill": { logo: "/logos/williamhill.png", url: "https://www.williamhill.com", backgroundColor: "#060a29" },
  winamax: { logo: "/logos/winamax.png", url: "https://www.winamax.fr", backgroundColor: "#e6e6e6" },
};

const FALLBACK_META: BookmakerMeta = {
  logo: "/logos/default-bookmaker.svg",
  url: "#",
};

const rawBookmakerMarginData: RawRegionalBookmakerRow[] = [
  { bookmaker_id: "betfair", bookmaker_key: "betfair_ex", bookmaker_title: "Betfair (Exchange)", market: "au", samples: 250, average_margin_percent: 2.05 },
  { bookmaker_id: "unibet", bookmaker_key: "unibet_au", bookmaker_title: "Unibet", market: "au", samples: 250, average_margin_percent: 7.27 },
  { bookmaker_id: "tabtouch", bookmaker_key: "tabtouch", bookmaker_title: "TABtouch", market: "au", samples: 250, average_margin_percent: 7.99 },
  { bookmaker_id: "pointsbet", bookmaker_key: "pointsbetau", bookmaker_title: "PointsBet", market: "au", samples: 250, average_margin_percent: 5.86 },
  { bookmaker_id: "betright", bookmaker_key: "betright", bookmaker_title: "Bet Right", market: "au", samples: 250, average_margin_percent: 7.25 },
  { bookmaker_id: "sportsbet", bookmaker_key: "sportsbet", bookmaker_title: "Sportsbet", market: "au", samples: 250, average_margin_percent: 6.79 },
  { bookmaker_id: "neds", bookmaker_key: "neds", bookmaker_title: "Neds", market: "au", samples: 250, average_margin_percent: 8.57 },
  { bookmaker_id: "ladbrokes", bookmaker_key: "ladbrokes_au", bookmaker_title: "Ladbrokes", market: "au", samples: 250, average_margin_percent: 8.27 },
  { bookmaker_id: "betr", bookmaker_key: "betr_au", bookmaker_title: "Betr", market: "au", samples: 250, average_margin_percent: 7.13 },
  { bookmaker_id: "tab", bookmaker_key: "tab", bookmaker_title: "TAB", market: "au", samples: 250, average_margin_percent: 7.08 },
  { bookmaker_id: "playup", bookmaker_key: "playup", bookmaker_title: "PlayUp", market: "au", samples: 250, average_margin_percent: 7.68 },
  { bookmaker_id: "matchbook", bookmaker_key: "matchbook_eu", bookmaker_title: "Matchbook (Exchange)", market: "eu", samples: 250, average_margin_percent: 2.56 },
  { bookmaker_id: "1xbet", bookmaker_key: "1xbet", bookmaker_title: "1xBet", market: "eu", samples: 250, average_margin_percent: 3.8 },
  { bookmaker_id: "marathonbet", bookmaker_key: "marathonbet", bookmaker_title: "Marathonbet", market: "eu", samples: 250, average_margin_percent: 6.37 },
  { bookmaker_id: "pinnacle", bookmaker_key: "pinnacle_eu", bookmaker_title: "Pinnacle", market: "eu", samples: 250, average_margin_percent: 3.8 },
  { bookmaker_id: "betonline", bookmaker_key: "betonlineag_eu", bookmaker_title: "BetOnline", market: "eu", samples: 250, average_margin_percent: 4.44 },
  { bookmaker_id: "coolbet", bookmaker_key: "coolbet_eu", bookmaker_title: "Coolbet", market: "eu", samples: 250, average_margin_percent: 5.2 },
  { bookmaker_id: "betsson", bookmaker_key: "betsson_eu", bookmaker_title: "Betsson", market: "eu", samples: 250, average_margin_percent: 6.72 },
  { bookmaker_id: "nordicbet", bookmaker_key: "nordicbet", bookmaker_title: "NordicBet", market: "eu", samples: 250, average_margin_percent: 6.9 },
  { bookmaker_id: "leovegas", bookmaker_key: "leovegas_se", bookmaker_title: "LeoVegas", market: "eu", samples: 250, average_margin_percent: 8.24 },
  { bookmaker_id: "codere", bookmaker_key: "codere_it", bookmaker_title: "Codere", market: "eu", samples: 250, average_margin_percent: 8.09 },
  { bookmaker_id: "tipico", bookmaker_key: "tipico", bookmaker_title: "Tipico", market: "eu", samples: 250, average_margin_percent: 7.67 },
  { bookmaker_id: "winamax", bookmaker_key: "winamax_de", bookmaker_title: "Winamax", market: "eu", samples: 250, average_margin_percent: 13.72 },
  { bookmaker_id: "betclic", bookmaker_key: "betclic_fr_eu", bookmaker_title: "Betclic", market: "eu", samples: 250, average_margin_percent: 10.18 },
  { bookmaker_id: "mybookie", bookmaker_key: "mybookieag_eu", bookmaker_title: "MyBookie", market: "eu", samples: 250, average_margin_percent: 6.82 },
  { bookmaker_id: "pmu", bookmaker_key: "pmu_fr_eu", bookmaker_title: "PMU", market: "eu", samples: 250, average_margin_percent: 11.47 },
  { bookmaker_id: "888sport", bookmaker_key: "888sport_eu", bookmaker_title: "888sport", market: "eu", samples: 250, average_margin_percent: 9.16 },
  { bookmaker_id: "william-hill", bookmaker_key: "williamhill_eu", bookmaker_title: "William Hill", market: "eu", samples: 250, average_margin_percent: 8.59 },
  { bookmaker_id: "everygame", bookmaker_key: "everygame", bookmaker_title: "Everygame", market: "eu", samples: 250, average_margin_percent: 8.02 },
  { bookmaker_id: "netbet", bookmaker_key: "netbet", bookmaker_title: "NetBet", market: "fr", samples: 250, average_margin_percent: 16.77 },
  { bookmaker_id: "atg", bookmaker_key: "atg_se", bookmaker_title: "ATG", market: "se", samples: 250, average_margin_percent: 5.27 },
  { bookmaker_id: "svenska-spel", bookmaker_key: "svenska_spel", bookmaker_title: "Svenska Spel", market: "se", samples: 250, average_margin_percent: 5.98 },
  { bookmaker_id: "campobet", bookmaker_key: "campobet_se", bookmaker_title: "CampoBet", market: "se", samples: 250, average_margin_percent: 6.39 },
  { bookmaker_id: "hajper", bookmaker_key: "hajper_se", bookmaker_title: "Hajper", market: "se", samples: 250, average_margin_percent: 7.48 },
  { bookmaker_id: "mr-green", bookmaker_key: "mrgreen_se", bookmaker_title: "Mr Green", market: "se", samples: 250, average_margin_percent: 8.74 },
  { bookmaker_id: "smarkets", bookmaker_key: "smarkets", bookmaker_title: "Smarkets (Exchange)", market: "uk", samples: 217, average_margin_percent: 1.58 },
  { bookmaker_id: "casumo", bookmaker_key: "casumo", bookmaker_title: "Casumo", market: "uk", samples: 250, average_margin_percent: 6.79 },
  { bookmaker_id: "grosvenor-casinos", bookmaker_key: "grosvenor", bookmaker_title: "Grosvenor", market: "uk", samples: 250, average_margin_percent: 6.88 },
  { bookmaker_id: "betfred", bookmaker_key: "betfred_uk", bookmaker_title: "Betfred", market: "uk", samples: 250, average_margin_percent: 8.51 },
  { bookmaker_id: "coral", bookmaker_key: "coral", bookmaker_title: "Coral", market: "uk", samples: 250, average_margin_percent: 7.45 },
  { bookmaker_id: "betway", bookmaker_key: "betway", bookmaker_title: "Betway", market: "uk", samples: 250, average_margin_percent: 7.86 },
  { bookmaker_id: "paddy-power", bookmaker_key: "paddypower", bookmaker_title: "Paddy Power", market: "uk", samples: 250, average_margin_percent: 8.88 },
  { bookmaker_id: "betvictor", bookmaker_key: "betvictor", bookmaker_title: "BetVictor", market: "uk", samples: 250, average_margin_percent: 8.14 },
  { bookmaker_id: "skybet", bookmaker_key: "skybet", bookmaker_title: "Sky Bet", market: "uk", samples: 250, average_margin_percent: 10.8 },
  { bookmaker_id: "boylesports", bookmaker_key: "boylesports", bookmaker_title: "BoyleSports", market: "uk", samples: 250, average_margin_percent: 10.87 },
  { bookmaker_id: "virgin-bet", bookmaker_key: "virginbet", bookmaker_title: "Virgin Bet", market: "uk", samples: 250, average_margin_percent: 9.61 },
  { bookmaker_id: "livescorebet", bookmaker_key: "livescorebet", bookmaker_title: "LiveScore Bet", market: "uk", samples: 250, average_margin_percent: 10.17 },
  { bookmaker_id: "betfair-sportsbook", bookmaker_key: "betfair_sb_uk", bookmaker_title: "Betfair Sportsbook", market: "uk", samples: 250, average_margin_percent: 14.63 },
  { bookmaker_id: "lowvig", bookmaker_key: "lowvig", bookmaker_title: "LowVig", market: "us", samples: 250, average_margin_percent: 4.93 },
  { bookmaker_id: "draftkings", bookmaker_key: "draftkings", bookmaker_title: "DraftKings", market: "us", samples: 250, average_margin_percent: 6.24 },
  { bookmaker_id: "bovada", bookmaker_key: "bovada", bookmaker_title: "Bovada", market: "us", samples: 250, average_margin_percent: 5.92 },
  { bookmaker_id: "betus", bookmaker_key: "betus", bookmaker_title: "BetUS", market: "us", samples: 250, average_margin_percent: 6.22 },
  { bookmaker_id: "betrivers", bookmaker_key: "betrivers", bookmaker_title: "BetRivers", market: "us", samples: 250, average_margin_percent: 6.92 },
  { bookmaker_id: "betmgm", bookmaker_key: "betmgm", bookmaker_title: "BetMGM", market: "us", samples: 250, average_margin_percent: 7.17 },
  { bookmaker_id: "fanduel", bookmaker_key: "fanduel", bookmaker_title: "FanDuel", market: "us", samples: 250, average_margin_percent: 5.9 },
  { bookmaker_id: "hard-rock-bet", bookmaker_key: "hardrockbet", bookmaker_title: "Hard Rock Bet", market: "us", samples: 250, average_margin_percent: 5.36 },
  { bookmaker_id: "bally-bet", bookmaker_key: "ballybet", bookmaker_title: "Bally Bet", market: "us", samples: 250, average_margin_percent: 5.97 },
  { bookmaker_id: "betparx", bookmaker_key: "betparx", bookmaker_title: "betPARX", market: "us", samples: 250, average_margin_percent: 6.74 },
  { bookmaker_id: "thescore", bookmaker_key: "thescorebet", bookmaker_title: "theScore Bet", market: "us", samples: 250, average_margin_percent: 6.34 },
  { bookmaker_id: "bet365", bookmaker_title: "Bet365", samples: 238, average_margin_percent: 9.08 },
  { bookmaker_id: "betano", bookmaker_title: "Betano", samples: 91, average_margin_percent: 7.44 },
  { bookmaker_id: "bwin", bookmaker_title: "bwin", samples: 104, average_margin_percent: 7.86 },
  { bookmaker_id: "10bet", bookmaker_title: "10bet", samples: 187, average_margin_percent: 8.62 },
  { bookmaker_id: "gtbets", bookmaker_title: "GTBets", samples: 142, average_margin_percent: 6.94 },
  { bookmaker_id: "stake", bookmaker_title: "Stake", samples: 94, average_margin_percent: 4.87 },
  { bookmaker_id: "22bet", bookmaker_title: "22Bet", samples: 212, average_margin_percent: 5.21 },
  { bookmaker_id: "20bet", bookmaker_title: "20Bet", samples: 168, average_margin_percent: 4.62 },
  { bookmaker_id: "melbet", bookmaker_title: "Melbet", samples: 96, average_margin_percent: 6.18 },
  { bookmaker_id: "betwinner", bookmaker_title: "BetWinner", samples: 128, average_margin_percent: 5.74 },
  { bookmaker_id: "parimatch", bookmaker_title: "Parimatch", samples: 182, average_margin_percent: 6.21 },
  { bookmaker_id: "dafabet", bookmaker_title: "DafaBet", samples: 214, average_margin_percent: 4.92 },
  { bookmaker_id: "sportsbet-io", bookmaker_title: "Sportsbet.io", samples: 236, average_margin_percent: 3.84 },
  { bookmaker_id: "cloudbet", bookmaker_title: "CloudBet", samples: 124, average_margin_percent: 5.37 },
  { bookmaker_id: "sbotop", bookmaker_title: "SBOTOP", samples: 24, average_margin_percent: 7.18 },
  { bookmaker_id: "m88", bookmaker_title: "M88", samples: 248, average_margin_percent: 3.27 },
  { bookmaker_id: "fun88", bookmaker_title: "Fun88", samples: 96, average_margin_percent: 4.63 },
  { bookmaker_id: "novibet", bookmaker_title: "Novibet", samples: 122, average_margin_percent: 4.41 },
  { bookmaker_id: "stoiximan", bookmaker_title: "Stoiximan", samples: 74, average_margin_percent: 4.72 },
  { bookmaker_id: "superbet", bookmaker_title: "Superbet", samples: 67, average_margin_percent: 6.08 },
  { bookmaker_id: "bet-at-home", bookmaker_title: "Bet-at-home", samples: 118, average_margin_percent: 4.36 },
  { bookmaker_id: "interwetten", bookmaker_title: "Interwetten", samples: 102, average_margin_percent: 6.54 },
  { bookmaker_id: "expekt", bookmaker_title: "Expekt", samples: 60, average_margin_percent: 6.18 },
  { bookmaker_id: "betsafe", bookmaker_title: "Betsafe", samples: 70, average_margin_percent: 5.87 },
  
];

export const bookmakerMarginData: RegionalBookmakerRow[] =
  rawBookmakerMarginData;